### ISSUE TITLE
Wi-Fi fails to start if toggled after desktop is running

### ISSUE THREAD

**Issue by pdsouza** [maruos/maruos#102]
### System Info

* Nexus 5X (bullhead)
* v0.6.4
* Open Gapps pico

### Steps to Reproduce

1. Toggle Wi-Fi ON
2. Start Maru Desktop
3. Toggle Wi-Fi OFF
4. Toggle Wi-Fi ON (it never connects)

Even if you stop Maru Desktop, it fails to reconnect until a reboot.

### Workaround

This is caused by the same issue in #98. 

1. Override `/lib/udev/rules.d/80-net-setup-link.rules` by placing a blank file in `/etc/udev/rules.d/80-net-setup-link.rules`:
```
maru@stretch:~$ sudo touch /etc/udev/rules.d/80-net-setup-link.rules
```

2. Reboot

**Comment by pdsouza** [comment]
Fixed in https://github.com/maruos/blueprints/commit/7c203c21fff25c061770962a08c88d169e35c301. This will be available in the next build v0.6.5.

**Comment by pdsouza** [comment]
0.6.5 is now available with the fix: https://github.com/maruos/builds/releases/tag/v0.6.5

**Comment by dianaxxyyzz** [comment]
It may be device specific cause on S9+ and Ubuntu is not a problem , but i applied this fix anyway

**Comment by pdsouza** [comment]
@dianaxxyyzz Yes, I think it may be specific to Debian and the device's kernel / Wi-Fi driver.
