### ISSUE TITLE
Audio distortion when using a BT headset for calls on the N5

### ISSUE THREAD

**Issue by pdsouza** [maruos/maruos#104]
I am getting a lot of distortion when making or receiving calls when I have a BT headset paired with the N5 running Maru 0.6.

This appears to be an issue on Android 8.1 Oreo due to some changes in the BT stack.

References:
https://forum.xda-developers.com/showpost.php?p=75688720&postcount=1456

**Comment by PifPof73** [comment]
Hi,
same problem inside my car calling system.
You do not understand a word - I can't use the speakerphone anymore.

N5, Maru 0.6, speakerphone: Bluetooth 2.0 on Hyundai iX35

Greetings,
PifPof73

**Comment by Manouchehri** [comment]
Running into the same issue, thought it was just the Nexus 5 being old at first. Is it possible to enable aptX by default?

**Comment by meiser79** [comment]
FYI, there's a fix available:

https://github.com/zeDDer/device_lge_hammerhead/commit/1834ec9c5037a7483e65e545c2bd05b6616899d9
https://github.com/zeDDer/android_hardware_broadcom_libbt/commit/68d1e3d7fd952ef07976b6775f6d070af9df348e

More info in the following XDA thread:
https://forum.xda-developers.com/showpost.php?p=79753114&postcount=16

**Comment by PifPof73** [comment]
It would be nice, if you could add this fix to the next v0.6.7 as I am still using Nexus 5 (even if it is old).

**Comment by pdsouza** [comment]
Oh wow, glad to learn that there's finally a fix available!

@PifPof73 I will get this merged in for our next release.

**Comment by pdsouza** [comment]
**Update**

We don't modify `android_hardware_broadcom_libbt` in Maru so we automatically received the patch from LineageOS that was merged in https://github.com/LineageOS/android_hardware_broadcom_libbt/commit/52a430b66e26492ea8c81d804864acad810af082.

All we should need to do is enable the config patch https://github.com/LineageOS/android_device_lge_hammerhead/commit/1de5d63fe2a8ee332eef53bc52d1fc7457d59dcb in our hammerhead device tree. I'll patch and test shortly.

**Comment by pdsouza** [comment]
Patched our device tree: https://github.com/maruos/android_device_lge_hammerhead/commit/6a563e8d706940d4038da4a97beb782b30e13a08

@meiser79 @PifPof73 

It works! I tested and confirmed clear calling via my BT earphones after applying these patches. This will be available in 0.6.7.

**Comment by pdsouza** [comment]
@meiser79 @PifPof73 0.6.7 is now available with this fix - please upgrade. And thanks for your help fixing this issue!

**Comment by PifPof73** [comment]
Hi pdsouza,
thank you very much, I installed 0.6.7 yesterday and will do some tests now.

The hammerhead is loosing it's bluetooth connection from time to time (still) and since 0.6.7 I am not able to get wearOs running to connect my smartwatch with maru.
I will do some further investigations and open new issues if necessary.

Let me know, if I can do some testing stuff / collect informations / logs etc.
Cheers,
PifPof73

**Comment by pdsouza** [comment]
@PifPof73 Yes, please open further issues and we will discuss how we can debug and fix.
