### ISSUE TITLE
Download section of the web site show nothing.

### ISSUE THREAD

**Issue by DQvsRA** [maruos/maruos#105]
The page - https://maruos.com/downloads/ give me this:
"Oops, something went wrong fetching the latest releases."
<img width="834" alt="Screenshot 2019-03-12 at 16 56 15" src="https://user-images.githubusercontent.com/442111/54215199-d3058800-44e7-11e9-95cf-e89cde7e1f17.png">

**Comment by TMartinPPC** [comment]
Very strange. It's working for me. @pdsouza might need to investigate.
![maru_download](https://user-images.githubusercontent.com/1407126/54216556-40052780-44c0-11e9-8783-c1aa58fb0f57.png)

**Comment by pdsouza** [comment]
@DQvsRA Are you still seeing this or was this a temporary error? The downloads page uses the GitHub API to fetch our latest releases so it's possible it was related to the GitHub service incident today: https://www.githubstatus.com/incidents/tj58y1kx7tqy

@TMartinPPC Thanks for verifying it works for you!

**Comment by mustafaozhan** [comment]
I confirm that i do not have same problem anymore, It fixed 😄 👍

**Comment by pdsouza** [comment]
Closing this since we have confirmation that the downloads page is working. Please feel free to re-open if you still have an issue.

**Comment by DQvsRA** [comment]
Looks like problem solved. Thanks everyone!
