### ISSUE TITLE
debian on maru can't output sound.

### ISSUE THREAD

**Issue by JackWang47** [maruos/maruos#107]
Hi!
When using Maru Desktop mode,I found that the HDMI will only output the sound comes from Android system,not the debian. Is there a way to output the sound from debian?

**Comment by pdsouza** [comment]
No audio support from Maru Desktop / Debian right now, but we are testing out a possible solution. I should make this explicitly clear for everyone and will add this to our FAQ.

**Comment by JackWang47** [comment]
Thank you!
I get that,now.
