### ISSUE TITLE
Google Play and other apps?

### ISSUE THREAD

**Issue by patrioticcow** [maruos/maruos#11]
Is Google Play not supported? I tried manually installing it and it doesn't open on tap.

What am I missing?

Thanks

**Comment by patrioticcow** [comment]
My Bad, looks like there is a guide here: https://groups.google.com/forum/#!topic/maru-os/S8PUEqqK10M

**Comment by pdsouza** [comment]
Glad you found the guide, were you able to follow it successfully?

**Comment by patrioticcow** [comment]
Yes. It works like a charm. I managed to get all the android apps running and Maru works great
