### ISSUE TITLE
Can't add google calendar to default calendar apps

### ISSUE THREAD

**Issue by Zlopez** [maruos/maruos#113]
I tried to add my google calendar to default calendar apps, but each time I get `Can't connect to server`.

How to reproduce:
1. Open Calendar
2. Open Settings
3. Add account
4. Type your gmail
5. Click NEXT
6. Choose Exchange
7. Type password
8. Click NEXT
9. Click NEXT

Current output:
`Can't connect to server` 

Expected output:
Calendar is added

**Comment by pdsouza** [comment]
Thanks for the report!

A few more questions:
1. Which device?
2. Do you have Google Apps installed?

My N5X is running a development build of Maru 0.6 and I have my Google Calendar showing up in the default Calendar app. However, I did not add it manually like you did - it just showed up after going through the Setup Wizard after installing Open Gapps the first time.

I'll have to test on a fresh device and see what's going on.

**Comment by Zlopez** [comment]
@pdsouza 
1. Nexus 5
2. I don't have Google Apps installed and I don't want them, I'm just looking for way to add Google calendar without installing Google Apps.

**Comment by utzcoz** [comment]
@Zlopez The Google calendar needs Google Play Service installed. What you need might be https://support.google.com/calendar/answer/10041132?hl=en.
