### ISSUE TITLE
Port for Pocophone F1

### ISSUE THREAD

**Issue by Limb3r** [maruos/maruos#116]
Great work and immense potential for maru os, no doubt. A geeks's dream on a budget. Which is why it seems strange to me that a uniquely popular budget flagship like the Pocophone is getting no support. It would easily attract the right crowd in their numbers to the Maru project. This seems important to my thinking since Maru is built from the ground up for every device, thus there's only so much that the small group of developers can reasonably be able to port before it goes mainstream. So, I would think that devices should be carefully selected for most userbase penetration.
For example, a port for the Galaxy s9+, that is a relatively expensive device with bootloader issues AND that already has LinuxOnDex out of the box (so to speak), should rank below porting for the Pocophone.
To my mind.

**Comment by bju2000** [comment]
It's still before the test, but I personally made it into a mix 2s model. However, the problem is that the base source (Lineage 15.1) is not enough and it is made with phh-gsi treble instead.

**Comment by utzcoz** [comment]
If anyone has interesting in porting MaurOS for Pocophone F1, you can follow https://maruos.com/docs/developer/#structure for it. If you have question about porting, you can create a new discussion at this repo for it. Feel free to reopen this issue if you have problem.
