### ISSUE TITLE
doc: Add more information about how to port MaruOS to new device

### ISSUE THREAD

**Issue by utzcoz** [maruos/maruos#117]
@pdsouza Many people want to find the detail to port MaruOS to new device in mailing list in recent days. If someone is familiar with AOSP or MaruOS, she/he can do it very quickly, and fix bugs she/he encounters. But for someone isn't familiar, current document is not very useful for she/him. Maybe we can append detail to port MaruOS, including how to enable LXC in kernel, how to import MaruOS device config, and how to build and test Linux rootfs, to document. And hope it will help other possible contributors can get more background knowledge to contribute to MaruOS.

**Comment by utzcoz** [comment]
@pdsouza The porting for kernel is fixed, and we should copy the origin defconfig file, and append essential missed configs to it. We can extract those essential configs to our before porting case, and use script to do it. If we can do it, the porting user should use our script to generate new defconfig which supports MaruOS. And then he/she should focus on device porting only. If there are some errors for specific device, he/she can post it to community, and you and other users can help he/she to fix it. Ideally, it will help to ease work to port MaruOS to a new device.

**Comment by pdsouza** [comment]
An automated script for adding the essential options to the stock device defconfig would be cool. It would be self-documenting as well. There are only a few essential options needed in the defconfig:

```
CONFIG_CGROUP_DEVICE=y
CONFIG_CPUSETS=y
CONFIG_DEVTMPFS=y
CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
CONFIG_NAMESPACES=y
CONFIG_SYSVIPC=y
```

And we must remember to remove any namespace blacklists like `# CONFIG_PID_NS is not set`.

**Comment by utzcoz** [comment]
@pdsouza I see the document contains the command to check `LXC` kernel config, and I think its enough for porting user. So I close the issue.
