### ISSUE TITLE
Port for OnePlus 6t McClaren

### ISSUE THREAD

**Issue by bf8392** [maruos/maruos#119]
Would love to see Maru on the OnePlus 6t McLaren. It has an awful lot of ram to use and would be a real good device! If dash charging works, and I can install apps from Google play, I would get it immediately!

**Comment by bd8392** [comment]
Sorry was wrongfiully posted on the wrtong forum...

**Comment by bd8392** [comment]
Is there any chance to see this? Maybe you don't have to develop the kernel yourself...just implement it from another distro if possible =). Franco Kernel or something like that =) I love the approach of your OS!

**Comment by bd8392** [comment]
Any news on this?

**Comment by pdsouza** [comment]
Check out our developer forum to keep an eye on which ports are going on. I
don't recall the 6T is being worked on yet though.

**Comment by bd8392** [comment]
Okay thank you :-) you know how to get to the developer forum? Is there a chance to get the oneplus 6t ported ? Or is there a manual how I can do it myself? (For rather unexperienced useres in porting)

**Comment by pdsouza** [comment]
Dev forum can be found here: https://groups.google.com/forum/#!forum/maru-os-dev
Please see our docs for porting guides (high-level): https://maruos.com/docs/developer/

**Comment by utzcoz** [comment]
If anyone has interesting in porting MaurOS for OnePlus 6T, you can follow https://maruos.com/docs/developer/#structure for it. If you have question about porting, you can create a new discussion at this repo for it. Feel free to reopen this issue if you have problem.
