### ISSUE TITLE
BT keyboards and mice do not register events in Android

### ISSUE THREAD

**Issue by pdsouza** [maruos/maruos#12]
After you successfully pair up a BT keyboard and mouse in Android, key presses or mouse movement is not registered in Android. However, they do register on the desktop.

This was actually by design to quickly get around the issue of duplicate events in Android and Maru Desktop. This is done by reserving (dropping) the devices from Android's input stack so they are only registered by the desktop.

A simple solution would be to only route the events to the desktop if the device is connected to HDMI and the desktop is active.

Ideally, it would be nice for users to be able to configure where there key presses and cursor movements are routed.

Related forum posts:
https://groups.google.com/d/msg/maru-os/_TL63qbNsKs/SnCAUuR0BAAJ
https://groups.google.com/forum/#!topic/maru-os/pEBouD5SSuw

**Comment by gantner** [comment]
One thought that struck me was I could be more productive if a virtual mirror of my android was a window on my Debian desktop. Then I could respond to text, chat and such and such without leaving my keyboard.

**Comment by dianaxxyyzz** [comment]
/sys/devices/virtual/graphics/fb1/connected tell if hdmi is connected ,so if is nto conneted , mouse can be sent to android

**Comment by pdsouza** [comment]
We have a proposal to fix this in https://github.com/maruos/maruos/issues/97

**Comment by pdsouza** [comment]
This has been fixed with dynamic input switching (#97) and released in 0.6.
