### ISSUE TITLE
It might be a waste of time, but...

### ISSUE THREAD

**Issue by bju2000** [maruos/maruos#120]
It might be a waste of time, but is there room for Chromium os, Fuchsia, besides Debian?

**Comment by utzcoz** [comment]
@bju2000 ChromiumOS supports to run Linux app based on its Project Crostini. Its Linux distro is based on Debian or Ubuntu in my memory. Maybe you can check ChromiumOS' document to get instruction to run Linux app on it. For Fuchsia, sorry, I don't know detail about running Linux app. MaruOS now can only run on Android phone.

**Comment by pdsouza** [comment]
Closing this due to staleness. Please re-open if you have further questions.
