### ISSUE TITLE
Questions: vs code

### ISSUE THREAD

**Issue by cambo2015** [maruos/maruos#124]
So since linux is installed, can I install and use vs code in phone mode + the command line? I need to use vs code away from an actual computer(on phone). T.I.A.

**Comment by diego-o-olmedo** [comment]
You can get vs code running on another platform with some extensions but as vs code is a git-scm gui you must need to run a compiled git as well as platform dependend extensions for compiling that would useful in vs code. However intellisense can work seamlessly.
https://headmelted.com/introducing-archie-cbf77a7a64fb
You just need to use archie docker to make a build for your platform as maruOS was build for you.
Hope it is useful
