### ISSUE TITLE
sailfish/marlin: Show vendor image mismatch alert dialog

### ISSUE THREAD

**Issue by utzcoz** [maruos/maruos#125]
Every boot, Android will show vendor image mismatch alert dialog.

> A vendor image mismatch has been detected. Typically this means your vendor image is out of date. Please ensure your vendor image matches OPM4.171019.021.P1.

After some digging, I have figured the reason. Sailfish and marlin support full treble, and it will trigger compatibility checking, including device manifest with framework manifest, device matrix with framework matrix, and framework matrix and runtime infor. In sailfish and marlin, the checking is failed in framework matrix and runtime info. The framework matrix includes kernel defconfig information, generated from vts kernel config data(see the definition of `system_compatibility_matrix.xml` in `build` directory). We have enable `SYSVIPC` to support `MaruOS`, but the `SYSVIPC` in `system/compatibility_matrix.xml` is disabled. So the checking between framework matrix and runtime info is failed, which caused the compatibility checking failed.

The checking code is in `system/libvinfVintfObject.cpp->checkCompatibility`.

**Comment by utzcoz** [comment]
There is a log for it:

> W zygote64: VintfObject.verify() returns 1: Runtime info and framework compatibility matrix are incompatible: For config CONFIG_SYSVIPC, value = y but required n

**Comment by utzcoz** [comment]
To fix this problem, there are some explicit solutions:

1. Don't show alert dialog. MaruOS modification will break the kernel compatibility. So the compatibility will be failed always. The simple and useful choice is to disable the function to show alert dialog for user. And it will affect all devices.
2. We can copy the current `system/compatibility_matrix.xml` with kernel defconfig from system, and modify the kernel defconfig to stay same with MaruOS modification. It will device maintainer to maintain it with system updating. I have tested it with pixel with below module script:

```
LOCAL_PATH := $(call my-dir)
# Override Framework Compatibility Matrix
# The compatibility_matrix.xml is copied from $OUT/system/compatibility_matrix.xml,
# which is generated by build system. We modify the its kernel defconfig to stay the
# same with maruos modification of kernel defconfig.
# So we should upgrade it when system updating.
include $(CLEAR_VARS)
LOCAL_MODULE := override_system_compatibility_matrix.xml
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_STEM := compatibility_matrix.xml
LOCAL_MODULE_PATH := $(TARGET_OUT)
LOCAL_OVERRIDES_PACKAGES := system_compatibility_matrix.xml
LOCAL_PREBUILT_MODULE_FILE := $(LOCAL_PATH)/compatibility_matrix.xml
include $(BUILD_PREBUILT)
```
3. Disable compatibility checking between runtime info and framework compatibility matrix(`system/compatibility_matrix.xml`). It will add another project(`system/libvinf`)  to MaruOS custom repo, and will increase the difficult of maintaining.

For me, I prefer to select choice 1, and feel fine for choice 2, but I don't like choice 3. @pdsouza Which choice would you like?

**Comment by utzcoz** [comment]
@pdsouza I select the choice 2, and maintain custom `compatibility_matrix.xml`. If there are other devices have the same problem, maybe we can consider to fix it in `frameworks/base`.

**Comment by pdsouza** [comment]
@utzcoz Thank you! Choice 2 is great for now, since Pixel is the only device with this issue. As we support more full Treble devices, we can consider adding this override to `vendor/maruos` so that all devices can simply include it.
