### ISSUE TITLE
settings: Extract MaruOS desktop settings to a single app

### ISSUE THREAD

**Issue by utzcoz** [maruos/maruos#127]
From `Android N`, `Settings` support extra settings.  If we assign action `com.android.settings.action.EXTRA_SETTINGS`(in `SettingsLib` `TileUtils`) to category `Activity`, the `TileUtils`' `getCategories` will find this `Activity`, and add it to the `Settings`' page.

Maybe we can create a single app, and implement the content of  `MaruOS` desktop to this app. Yes, this app should include the dependency of `SettingsLib`. After that, we can drop the modification of `Settings`, and remove it from `MaruOS` custom repository.

**Comment by utzcoz** [comment]
@pdsouza  can help add `settings` or other more meaningful label to this issue? Thanks.

**Comment by pdsouza** [comment]
@utzcoz Yes, I noticed this too when porting from M to N. We should definitely do this. This app can also manage the desktop rootfs (#99).

**Comment by utzcoz** [comment]
Okay, maybe we can add settings function to this app now, just from zero to one.

**Comment by utzcoz** [comment]
@pdsouza If need, I can create a project to do it in my repository to start to extract `MaruOS` desktop settings to a single app.

**Comment by pdsouza** [comment]
@utzcoz Yeah that would be great if you have the time! Thanks!

**Comment by utzcoz** [comment]
Maru desktop settings depends on `Settings` code, instead of `SettingsLib` only, and current `Settings` doesn't provide a core library for other app, which is done in `master` branch. So I will check whether it's easy to archive the same function without `Settings` dependency.

**Comment by pintaf** [comment]
Hey ! Did someone started working on this ? I'm willing to continue the work

**Comment by utzcoz** [comment]
@pintaf I am working for it, and I push code to project [vendor_maruos_packages_apps_MaruSettings](https://github.com/utzcoz/vendor_maruos_packages_apps_MaruSettings). I just fix the build problem of MaruSettings with maruos modification to Settings. So if you have interested, you can checkout the code, and add your work.

**Comment by pintaf** [comment]
Thanks for the heads up. I've forked the project, and will contribute when I can

**Comment by utzcoz** [comment]
@pdsouza @pintaf , I have pushed a work version to my repository [MaruSettings](https://github.com/utzcoz/vendor_maruos_packages_apps_MaruSettings). And I have added a integrate it to `MaruOS` manual to `README.md`, so you can download and test it. After integrating, we can see another `Desktop` entry on `Settings` dashboard homepage bottom. It looks like the same as origin `Desktop` item, and works fine as it too. I also added the detail to the `README.md`, so we can discuss whether it fits our need.

**Comment by pintaf** [comment]
Hello @utzcoz 
I checked the source. I'll try to integrate this in my LOS16 build. This seems like a really good job.
I want to add the possibility to run mcprepare from the settings app too and maybe also the possibility to dl the rootfs.
It'll be easier to work with your app than doing this on the LOS settings.
Thanks !

**Comment by utzcoz** [comment]
In Android 10, the settings can't find custom fragment class with its `ClassLoader`. So we should implement preference content to outer settings activity.

**Comment by utzcoz** [comment]
@pdsouza if we start to maru-0.7, I can collaborate with @pintaf to do it for maru-0.7 based on @pintaf 's work. Maybe the maru-0.7 can be a more suitable place to integrate it. Also it can integrate some thoughts in [Some suggestions for future releases](https://github.com/maruos/maruos/issues/153) by @twaik.

**Comment by pdsouza** [comment]
@utzcoz Yes, let's do that. I've already begun to set up a basic `maru-0.7` manifest. You can see my early work here: https://github.com/pdsouza/manifest/tree/maru-0.7. I will merge this to our main manifest repo once I confirm I can get a LOS16 build working without issues. Then I can accept PRs on that branch to integrate `MaruSettings` and other suggestions by @twaik.

**Comment by twaik** [comment]
I do not think I will be ready for release soon. But there is a possibility that I can adaptate mflinger to be both X11- and Surfaceflinger client.
Actually there is a 3rd solution. I used it for Termux project. I implemented basic wayland server that can be output only for XWayland. It implements a basic shared memory based output and keyboard/mouse/etc input. I stucked at touchpad emulation, but it is unneded if we use external devices for input. There were some lags on aarch64 based devices but I think I know how to get rid of them.

**Comment by pintaf** [comment]
@Ready to work on that with you.
I just set up again a build machine for maru building (will do it for Aquarus X2), so really looking forward pushing things further.

**Comment by pintaf** [comment]
> I do not think I will be ready for release soon. But there is a possibility that I can adaptate mflinger to be both X11- and Surfaceflinger client.
> Actually there is a 3rd solution. I used it for Termux project. I implemented basic wayland server that can be output only for XWayland. It implements a basic shared memory based output and keyboard/mouse/etc input. I stucked at touchpad emulation, but it is unneded if we use external devices for input. There were some lags on aarch64 based devices but I think I know how to get rid of them. The [basic code without Activity adaptations](https://github.com/twaik/termux-x11/tree/master/app/src/main/jni) is pretty simple.

I would love to help you on that, but I lack low level knowledge. I'm normally more a frond end dev. I don't even totally understand what you wanna do, but if you need help, tell me, I'll do my best to help, I'm a fast learner

**Comment by utzcoz** [comment]
Okay, the `MaruSettings` has been added to maru-0.7, and it works with the basic functions. Although it has some works to be done, I will create new issue for the specific problem,  so I close this old and long issue.
