### ISSUE TITLE
Rockchip porting problem

### ISSUE THREAD

**Issue by yuxue521** [maruos/maruos#129]
This project is very good, I tried to transplant to rk3288（tinkeboard android 7.1.2）
I pulled the 0.5 version
I am connected to hdmi information prompt Maru Desktop running
click Mirror phone 
I found the same content as the main interface and didn't see the linux x11 interface. I don't know why I found this error.

**Comment by utzcoz** [comment]
@yuxue521 Maybe you can see the issue [mmap failed on rockchip devices](https://github.com/maruos/blueprints/issues/11) in project blueprints.

**Comment by yuxue521** [comment]
@utzcoz  
Thank you, but I don't know how to modify #include <fcntl.h>
I found information like logs
11-19 07:47:00.617   235   235 E Surface : Surface::lock failed, already locked
11-19 07:47:00.618   235   235 E mflinger: failed to lock buffer
11-19 07:48:00.610   235   235 E Surface : Surface::lock failed, already locked
11-19 07:48:00.610   235   235 E mflinger: failed to lock buffer
11-19 07:49:00.609   235   235 E Surface : Surface::lock failed, already locked
11-19 07:49:00.610   235   235 E mflinger: failed to lock buffer
11-19 07:50:00.617   235   235 E Surface : Surface::lock failed, already locked
11-19 07:50:00.618   235   235 E mflinger: failed to lock buffer
11-19 07:51:00.618   235   235 E Surface : Surface::lock failed, already locked
11-19 07:51:00.619   235   235 E mflinger: failed to lock buffer
11-19 07:52:00.618   235   235 E Surface : Surface::lock failed, already locked
11-19 07:52:00.618   235   235 E mflinger: failed to lock buffer
11-19 07:53:00.591   235   235 E Surface : Surface::lock failed, already locked
11-19 07:53:00.592   235   235 E mflinger: failed to lock buffer
11-19 07:54:00.584   235   235 E Surface : Surface::lock failed, already locked
11-19 07:54:00.584   235   235 E mflinger: failed to lock buffer

kernel/include/linux/fcntl.h   
`#ifndef _LINUX_FCNTL_H
#define _LINUX_FCNTL_H

#include <uapi/linux/fcntl.h>

/* list of all valid flags for the open/openat flags argument: */
#define VALID_OPEN_FLAGS \
        (O_RDONLY | O_WRONLY | O_RDWR | O_CREAT | O_EXCL | O_NOCTTY | O_TRUNC | \
         O_APPEND | O_NDELAY | O_NONBLOCK | O_NDELAY | __O_SYNC | O_DSYNC | \
         FASYNC | O_DIRECT | O_LARGEFILE | O_DIRECTORY | O_NOFOLLOW | \
         O_NOATIME | O_CLOEXEC | O_PATH | __O_TMPFILE)

#ifndef force_o_largefile
#define force_o_largefile() (BITS_PER_LONG != 32)
#endif

#if BITS_PER_LONG == 32
#define IS_GETLK32(cmd)         ((cmd) == F_GETLK)
#define IS_SETLK32(cmd)         ((cmd) == F_SETLK)
#define IS_SETLKW32(cmd)        ((cmd) == F_SETLKW)
#define IS_GETLK64(cmd)         ((cmd) == F_GETLK64)
#define IS_SETLK64(cmd)         ((cmd) == F_SETLK64)
#define IS_SETLKW64(cmd)        ((cmd) == F_SETLKW64)
#else
#define IS_GETLK32(cmd)         (0)
#define IS_SETLK32(cmd)         (0)
#define IS_SETLKW32(cmd)        (0)
#define IS_GETLK64(cmd)         ((cmd) == F_GETLK)
#define IS_SETLK64(cmd)         ((cmd) == F_SETLK)
#define IS_SETLKW64(cmd)        ((cmd) == F_SETLKW)
#endif /* BITS_PER_LONG == 32 */

#define IS_GETLK(cmd)   (IS_GETLK32(cmd)  || IS_GETLK64(cmd))
#define IS_SETLK(cmd)   (IS_SETLK32(cmd)  || IS_SETLK64(cmd))
#define IS_SETLKW(cmd)  (IS_SETLKW32(cmd) || IS_SETLKW64(cmd))

#endif`

**Comment by utzcoz** [comment]
@yuxue521 I don't change `fcntl.h`. My patch is to let rockchip gralloc drm set fd to read and write when it transforms primary handle to fd for upper service, SurfaceFlinger, and it needs include `fcntl.h`.

**Comment by yuxue521** [comment]
@utzcoz  My rk3288 may not need this patch
# ls /dev/fd -l
ls /dev/fd -l
lrwxrwxrwx. 1 root root 13 Nov 19 09:49 /dev/fd -> /proc/self/fd
#
I suspect that it has a relationship with rockchips' dual screen patch. I need to check it out.

**Comment by yuxue521** [comment]
@utzcoz I try to understand what you mean.
Ret = drmPrimeHandleToFD(info->fd, gem_handle, 0,
&handle->prime_fd);
Should be changed
Ret = drmPrimeHandleToFD(info->fd, gem_handle, O_RDWR,
&handle->prime_fd);
Is this what you mean?

**Comment by yuxue521** [comment]
I just tested I found this problem
systemctl status maru-mflinger-client
[1;32m鈼?[0m maru-mflinger-client.service - mflinger client for X11
   Loaded: loaded (/lib/systemd/system/maru-mflinger-client.service; enabled)
   Active: [1;32mactive (running)[0m since Fri 2013-01-18 08:50:35 UTC; 6 year
s 10 months ago
 Main PID: 106 (mclient)
   CGroup: /system.slice/maru-mflinger-client.service
           鈹斺攢106 /usr/bin/mclient

Nov 20 00:37:00 jessie mclient[106]: [1;31merror mmaping buffer: Permission den
ied[0m
Nov 20 00:37:00 jessie mclient[106]: [1;31mMLockBuffer failed![0m
Nov 20 00:38:00 jessie mclient[106]: [1;31merror mmaping buffer: Permission den
ied[0m
Nov 20 00:38:00 jessie mclient[106]: [1;31mMLockBuffer failed![0m
Nov 20 00:39:00 jessie mclient[106]: [1;31merror mmaping buffer: Permission den
ied[0m
Nov 20 00:39:00 jessie mclient[106]: [1;31mMLockBuffer failed![0m
Nov 20 00:40:00 jessie mclient[106]: [1;31merror mmaping buffer: Permission den
ied[0m
Nov 20 00:40:00 jessie mclient[106]: [1;31mMLockBuffer failed![0m
Nov 20 00:41:00 jessie mclient[106]: [1;31merror mmaping buffer: Permission den
ied[0m
Nov 20 00:41:00 jessie mclient[106]: [1;31mMLockBuffer failed![0m
root@jessie:/#

**Comment by yuxue521** [comment]
@utzcoz 
Thank you for your advice, I have successfully run maruos

**Comment by pdsouza** [comment]
@yuxue521 Nice! Very cool to know Maru runs on a SBC like Tinkerboard!

**Comment by yuxue521** [comment]
Thanks for this project, I am going to close this question

**Comment by utzcoz** [comment]
@yuxue521 do you change the permission of `fd` in `gralloc_drm`? I found your delete message contains the mmap permission denied log. If yes, @pdsouza maybe we can add it to our FAQ.

**Comment by yuxue521** [comment]
@utzcoz 
Yes, I changed it

**Comment by utzcoz** [comment]
@yuxue521 okay. @pdsouza Maybe we should add this problem to FAQ. If yes, I will create a new issue to do it.

**Comment by pdsouza** [comment]
@utzcoz Maybe we can add it to the Porting Guide instead of FAQ? FAQ is more high-level user issues. How about here: https://maruos.com/docs/developer/porting.html#known-porting-issues? I'm open to your ideas.

**Comment by utzcoz** [comment]
@pdsouza Okay, I create a new issue, and will add it to porting issues page.
