### ISSUE TITLE
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid

### ISSUE THREAD

**Issue by yuxue521** [maruos/maruos#130]
@pdsouza 
I am running on tinkeboard rk3288

Operate via HDMI
Sudo systemctl start ssh
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

I can only connect via adb
rk3288:/ # lxc-attach -n default
lxc-attach -n default
su
root@stretch:/# chmod u+s  /usr/bin/sudo
chmod u+s  /usr/bin/sudo
root@stretch:/# chmod u+s  /usr/bin/sudo
root@stretch:/# systemctl start ssh
systemctl start ssh
root@stretch:/# ifconfig

Connected via ssh

`Linux stretch 4.4.143 #90 SMP PREEMPT Fri Nov 15 19:46:44 CST 2019 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
maru@stretch:~ ls
Desktop
maru@stretch:~ cat /etc/sudoers
cat: /etc/sudoers: Permission denied
maru@stretch:~ vi /etc/sudoers 
maru@stretch:~ sudo vi /etc/sudoers
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
maru@stretch:~ sudo vi /etc/sudoers
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
maru@stretch:~
maru@stretch:~ sudo -l
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
maru@stretch:~`

**Comment by utzcoz** [comment]
@yuxue521 maruos mounts Linux in `/data` partition, and most of OEM assigns `nosuid` to `/data` partition in its `fstab` file. You should remove `nosuid` in `rk3328`'s `fstab`, and flash your device, the `nosuid` error will disappear ideally.

**Comment by yuxue521** [comment]
This problem is solved perfectly, thank you

**Comment by QGB** [comment]
```
shell@android:/ $ ll /system/xbin/busybox
-rwsr-xr-x root     root       529876 2008-08-01 20:00 busybox
shell@android:/ $ /system/xbin/busybox whoami
shell
shell@android:/ $ /system/xbin/busybox id
uid=2000(shell) gid=2000(shell) groups=1003(graphics),1004(input),1007(log),1009(mount),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats)

```
