### ISSUE TITLE
maruos reboot bug

### ISSUE THREAD

**Issue by yuxue521** [maruos/maruos#135]
marous connect hdmi everything works
When my machine restarts, I do n’t unplug the hdmi and boot again. Maruos has no interface. I need to unplug the hdmi cable and plug it in again to start the desktop. I think this should be a bug. Can you tell me the location of the control code when it starts? I want to fix it.

**Comment by pdsouza** [comment]
Oh, weird. I keep my Nexus 5 plugged in always and the desktop starts up even if I do a restart on the phone without unplugging the HDMI cable. I wonder why it is not working on your device...

You can find the external display detection code here: https://github.com/maruos/android_platform_frameworks_base/blob/maru-0.6/services/core/java/com/android/server/mperspective/PerspectiveService.java#L422

**Comment by yuxue521** [comment]
Thanks for the hint, i have fixed this problem on tinkeboard

I found that tinkeboard is easier to port maruos. This default supports dual screens.
