### ISSUE TITLE
 Screen output to surfaceview or NativeActivity

### ISSUE THREAD

**Issue by yuxue521** [maruos/maruos#136]
@pdsouza @utzcoz 

After reading the code many times I know that the most critical data transfer is in
`
ANativeWindow_Buffer outBuffer;
        buffer_handle_t handle;
        status_t err = s->lockWithHandle(&outBuffer, &handle, NULL);
.......
    fdptr = (int *) CMSG_DATA(cmsg);
    memcpy(fdptr, &fd, sizeof(int));
`
I try to output to Surfaceview or NativeActivity
I do not know what to do. My understanding is that passing the fb pointer to the surface layer cannot be associated with the application. The method I think of now is screen recording. The benefits of this can be output to the application, and can be freely controlled to display to the main screen or auxiliary screen, and full screen applications can intercept input

**Comment by yuxue521** [comment]
In order to achieve the maruos display to the main screen to solve the problem of screen overlap, I used the most stupid method, adding a layer of black background, I can not set the maruos black background can only use this method
`
static int createSurface(struct mflinger_state *state,
            uint32_t w, uint32_t h) {
 ret |= surface->setLayer(0x7fffffff/*get_layer(state->num_surfaces)*/);
 // ret |= surface->setLayerStack(state->layerstack);

int main() {

    struct mflinger_state state;
    state.num_surfaces = 0;
    state.layerstack = -1;
  ......
	sp<SurfaceComposerClient> client = new SurfaceComposerClient();
	sp<IBinder> dtoken(SurfaceComposerClient::getBuiltInDisplay(
            ISurfaceComposer::eDisplayIdMain));
			DisplayInfo dinfo;
    status_t status = SurfaceComposerClient::getDisplayInfo(dtoken, &dinfo);
	ALOGE("w=%d,h=%d,xdpi=%f,ydpi=%f,fps=%f,ds=%f\n", 
        dinfo.w, dinfo.h, dinfo.xdpi, dinfo.ydpi, dinfo.fps, dinfo.density);
    if (status)
        return -1;
    sp<SurfaceControl> surfaceControl = client->createSurface(String8("testsurface"),
            dinfo.w, dinfo.h, PIXEL_FORMAT_RGB_565, 0);
	/****************************Insert a black background to solve the problem of overlapping pictures****************************/
    SurfaceComposerClient::openGlobalTransaction();
    surfaceControl->setLayer(0x7ffffff0);//
	surfaceControl->setPosition(0, 0);//
    //surfaceControl->setAlpha(1.0f);
    SurfaceComposerClient::closeGlobalTransaction();
	surfaceControl->show();
	sp<Surface> surface = surfaceControl->getSurface();
 
	ANativeWindow_Buffer outBuffer;
	//Surface::SurfaceoutBuffer outBuffer;
	surface->lock(&outBuffer,NULL);//
    ssize_t bpr = outBuffer.stride * bytesPerPixel(outBuffer.format);
    android_memset16((uint16_t*)outBuffer.bits, 0x000000, bpr*outBuffer.height);
    surface->unlockAndPost();
	

    int len;
    struct sockaddr_un local;

    local.sun_family = AF_UNIX;

    /* add a leading null byte to indicate abstract socket namespace */
`
![IMG_20191203_103247](https://user-images.githubusercontent.com/23266515/70015478-6e7be300-15b8-11ea-9e22-c1e2dda96f0c.jpg)

**Comment by pdsouza** [comment]
@yuxue521 Oh, interesting! It looks like you are using two displays (HDMI and MIPI DSI maybe?) with your Tinker Board?

From your code sample it looks like you have modified mflinger to output the Linux display to DEFAULT_DISPLAY rather than DEFAULT_EXTERNAL_DISPLAY? Then maybe you use screen mirroring to show the display over HDMI as well? What happens if you rotate your display to portrait mode?

And what exactly do you mean by "screen overlap"? You mean overlapping with the Android screen on the main display?

**Comment by yuxue521** [comment]
@pdsouza 
Yes, I used two screens of edp + hdmi. The screen overlap means that the linux interface and the android interface are displayed at the same time (that is, you can see the android screen and the linux screen because the linux screen is transparent)
I removed
ret | = surface-> setLayerStack (state-> layerstack);
Let him show on the home screen

**Comment by yuxue521** [comment]
@pdsouza 
This result is not what I want, because I cannot dynamically switch to the android screen.
The ideal is to display the linux screen in an app, I can switch between android and linux at any time

**Comment by yuxue521** [comment]
@pdsouza Can you give advice to associate the linux screen with the app
I don't know if to manage it

**Comment by luka177** [comment]
Hmm crazy idea, stop surfaceflinger in android and output to /dev/fb0

**Comment by luka177** [comment]
https://unix.stackexchange.com/questions/18003/linux-lxc-deploying-images-with-tiniest-possible-x11

**Comment by luka177** [comment]
So it must look like:
1. We somehow stop all android gui releated services.
2. Start container with bind mounted /dev/fb0 or /dev/graphic/fb0 to /dev/fb0
3. Use it.
4. Stop container
5. Start android gui services again

**Comment by luka177** [comment]
setprop ctl.stop surfaceflinger will stop android from trying to shw something on screen
/etc/X11/xorg.conf  must look lile
```
    Section "ServerLayout"
	Identifier	"Layout0"
	Screen 		"Screen0"
        InputDevice     "touchscreen device here will do greate job" "CorePointer"
	InputDevice	"Keyboard0" ig "CoreKeyboard"
    EndSection

    Section "InputDevice"
	Identifier 	"Keyboard0"
	Driver 		"evdev"
	Option		"Device"	"/dev/input/eventx"
	Option		"Protocol"	"usb"
    EndSection

    Section "InputDevice"
	Identifier	"Mouse0"
	Driver		"mouse"
	Option		"Protocol"	"IMPS/2"
	Option		"Device"	"/dev/input/mice"
    EndSection

Section "InputDevice"
    Identifier     "touch screen device"
    Driver         "multitouch"
    Option         "Device" "/dev/input/eventx"
    # mouse should move as fast as finger and not faster
    Option         "AccelerationScheme" "none"
    # evdev has it, multitouch doesn't so it behaves like touchpad
#   Option         "IgnoreRelativeAxes" "True"
EndSection

    Section "Device"
    	Identifier	"Card0"
    	Driver		"fbdev"
    	Option		"fbdev" "/dev/graphics/fb0"
    	VendorName	"Unknown"
    	BoardName	"Unknown"
    EndSection

    Section "Screen"
	Identifier 	"Screen0"
    	Device		"Card0"
	DefaultDepth    24
    	SubSection      "Display"
        	Depth              	24
# Depends on display resolution
        	Modes			"1080x1920_60.00" 
    	EndSubSection
    EndSection
```

**Comment by luka177** [comment]
Soon will try on real hw

**Comment by luka177** [comment]
Butw ig next step is libhybris

**Comment by luka177** [comment]
Dynamic screen rotation will be problem

**Comment by luka177** [comment]
xrandr -o 0,1,2,3
will dynamicly but not very fast rotate screen tested on my pc

**Comment by luka177** [comment]
https://wiki.postmarketos.org/wiki/Display
some docs, rotation touchscreen

**Comment by luka177** [comment]
https://wiki.postmarketos.org/wiki/Display
some docs

**Comment by luka177** [comment]
Faced some problems
it see
```
cedric:/ # ls /dev/graphics/                                                                                                                                                                 
fb0
cedric:/ # ls /dev/                                                                                                                                                                          
__properties__   coresight-tmc-etf hbtp_vm      media2           msm_evrc_in        null                  ramdump_venus smd21            stml0xx_as    usf1         v4l-subdev7 
adsprpc-smd      cpu_dma_latency   hw_random    memcg            msm_g711alaw_in    port                  ramdump_wcnss smd22            stml0xx_ms    v4l-subdev0  v4l-subdev8 
android_mbim     cpuctl            hwbinder     memory_bandwidth msm_g711mlaw_in    ppp                   random        smd3             stune         v4l-subdev1  v4l-subdev9 
android_rndis_qc cpuset            i2c-2        mmi_sys_temp     msm_hweffects      psaux                 rfkill        smd36            subsys_adsp   v4l-subdev10 vga_arbiter 
apr_apps2        device-mapper     i2c-3        msm-rng          msm_mp3            ptmx                  rmi0          smd4             subsys_modem  v4l-subdev11 video0      
ashmem           diag              icesdcc      msm_aac          msm_multi_aac      pts                   rmnet_ctrl    smd5             subsys_venus  v4l-subdev12 video1      
at_usb0          dpl_ctrl          input        msm_aac_in       msm_qcelp          qce                   rmnet_ctrl1   smd6             subsys_wcnss  v4l-subdev13 video2      
at_usb1          drv2605           ion          msm_alac         msm_qcelp_in       qseecom               rmnet_ctrl2   smd7             tty           v4l-subdev14 video32     
avtimer          ecryptfs          jpeg0        msm_amrnb        msm_rtac           radio0                rmnet_ctrl3   smd8             tun           v4l-subdev15 video33     
bfqio            event-log-tags    keychord     msm_amrnb_in     msm_sps            ramdump_adsp          rtc0          smd_pkt_loopback uhid          v4l-subdev16 vndbinder   
binder           fd                kgsl-3d0     msm_amrwb        msm_thermal_query  ramdump_adsp_rh       s3203b        smdcntl0         uinput        v4l-subdev17 wcnss_ctrl  
block            fscklogs          kmsg         msm_amrwb_in     msm_wma            ramdump_memshare_DIAG sdsprpc-smd   smdcntl8         uio0          v4l-subdev2  wcnss_wlan  
bus              full              loop-control msm_amrwbplus    msm_wmapro         ramdump_memshare_FTM  sensors       snd              urandom       v4l-subdev3  xt_qtaguid  
ccid_bulk        fuse              mdss_rotator msm_ape          mtp_usb            ramdump_memshare_GPS  smd1          socket           usb-ffs       v4l-subdev4  zero        
ccid_ctrl        graphics          media0       msm_audio_cal    network_latency    ramdump_modem         smd11         stml0xx          usb_accessory v4l-subdev5  
console          hbtp_input        media1       msm_evrc         network_throughput ramdump_smem          smd2          stml0xx_akm      usb_ext_chg   v4l-subdev6  
cedric:/ # cat /dev/random > /dev/graphics/fb0
cat: xwrite: No such device
1|cedric:/ # 
```
