### ISSUE TITLE
sailfish/marlin: kernel panic when find files in /data

### ISSUE THREAD

**Issue by utzcoz** [maruos/maruos#140]
If I execute `find . -iname "*maru*"` in marlin, the device will reboot. After rebooting, I use command `adb shell pull /data/system/dropbox` to pull the dropbox files, and get kernel panic information from last kernel log:
```
....
[  153.444657] c3   2869 EXT4-fs error (device sda35): _ext4_fname_disk_to_usr:331: inode #134178: comm find: encrypted inode too small
[  153.444972] c3   2869 Aborting journal on device sda35-8.
[  153.445238] c3   2869 Kernel panic - not syncing: EXT4-fs (device sda35): panic forced after error
....
[  155.328402] c3   2869 Total active clients count: 0
[  155.328714] c3   2869 scm_call failed: func id 0xc2000301, arginfo: 0x1, args: 0x1, 0xffffffc0000d27fc, 0xffffffc00189cbb0, 0xfffffff7, ret: -1, syscall returns: 0x0, 0x0, 0x0
[  155.328725] c3   2869 set restart reason = 0x776655AA
[  155.328732] c3   2869 set restart msg = 'KP: EXT4-fs (device sda35): panic forced after error
[  155.328732] c3   2869 '
[  155.336307] Rebooting in 5 seconds..
[  160.336592] c3   2869 Kernel command line: console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=marlin user_debug=31 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 cma=32M@0-0xffffffff loop.max_part=7 buildvariant=userdebug veritykeyid=id:7e4333f9bba00adfe0ede979e28ed1920492b40f androidboot.bootdevice=624000.ufshc androidboot.verifiedbootstate=orange androidboot.veritymode=enforcing androidboot.keymaster=1 androidboot.serialno=HT69B0201443 androidboot.baseband=msm mdss_mdp.panel=1:dsi:0:qcom,mdss_dsi_samsung_s6e3ha3_wqhd_cmd:1:qcom,mdss_dsi_samsung_s6e3ha3_wqhd_cmd:cfg:split_dsi androidboot.slot_suffix=_b fpsimd.fpsimd_settings=0 app_setting.use_app_setting=0 kernelflag=0x00000000 debugflag=0x00000000 androidboot.hardware.revision=PVT radioflag=0x00000008 radioflagex1=0x00000000 radioflagex2=0x00000000 cpumask=0x00000000 androidboot.hardware.ddr=4096MB,Samsung,LPDDR4 androidboot.ddrinfo=00000001 androidboot.ddrsize=4GB androidboot.hardware.color=GRA00 androidboot.hardware.ufs=3[  160.336605] c3   2869 Going down for restart now
...
```
It looks like ext4-fs encrypted inode number is too small.

**Comment by pdsouza** [comment]
Interesting. This error is thrown here: https://github.com/maruos/android_kernel_google_marlin/blob/maru-0.6/fs/ext4/crypto_fname.c#L331. It looks like this check is referring to the filename itself?

Also, are you running `find` from Android or Linux?

**Comment by utzcoz** [comment]
From the panic log and code, it looks like Linux rootfs add many files to `/data`. And it maybe use almost of encrypted inode. My occasion is to run `find` in `Android` with `adb shell` in `/data` directory. I agree to invest more code to get more detail of `EXT4_CRYPTO_BLOCK_SIZE`.  From the code, I found `bullhead` uses `16` for `EXT4_CRYPTO_BLOCK_SIZE` too, @pdsouza  can you help me execute the same command in `Nexus 5x` to check whether `Nexus 5X` has the same problem?

**Comment by pdsouza** [comment]
Unfortunately both my Nexus 5Xs have died due to a hardware failure! I don't have an arm64 device to test until I get some new devices...

Can you check if you get a kernel panic without the Linux rootfs on `/data`?

**Comment by luka177** [comment]
If you need can try on arm64 cedric

**Comment by utzcoz** [comment]
If `Linux` works fine, this problem will not appear, so I close it.
