### ISSUE TITLE
PIXEL_FORMAT_BGRA_8888 to PIXEL_FORMAT_RGBA_8888

### ISSUE THREAD

**Issue by yuxue521** [maruos/maruos#144]
How to modify PIXEL_FORMAT_BGRA_8888 to PIXEL_FORMAT_RGBA_8888
I will output the screen to surfaceview but the color is abnormal

`    sp<SurfaceControl> surface = state->compositor->createSurface(
        name,
        w, h,
        PIXEL_FORMAT_BGRA_8888,
        0);`
I use binder to pass surface to mflinger

surfaceview->getHolder()-->jni-->surface>writeStrongBinder-binder-->mflinger
Surfaceview cannot use BGRA_8888 I use  holder.setFormat(PixelFormat.RGBA_8888);
Everything works fine but the colors are abnormal

Where is BGRA controlled？

**Comment by utzcoz** [comment]
`mclient` use `xlib` to retrieve `XImage`, and [it creates `XImage` with `ZPixmap` format](https://github.com/maruos/mflinger/blob/master/src/mclient/mclient.c#L153-L160). And then, it uses the method [copy_ximg_rows_to_buffer_mlocked](https://github.com/maruos/mflinger/blob/master/src/mclient/mclient.c#L66-L87) to copy the `XImage` content to buffer will be passed to `mflinger` directly, without position changing. From the code, the default format of `ZPixmap` is `BGRA_8888`. If you want to change it to `RGBA_8888`, maybe you should change bit sequence from `XImage` to `MBuffer` bits, just likes:

```c
*buf_row = *(ximg_row + 2); // R
*(buf_row + 1) = *(ximg_row + 1); // G
*(buf_row + 2) = *ximg_row; // B
*(buf_row + 3) = *(ximg_row + 3); // A
```
I don't check code in my work machine, it just pseudo code.

**Comment by yuxue521** [comment]
Thanks for your reply i will try

**Comment by yuxue521** [comment]
`    for (y = row_start; y < row_end; ++y)
    {
        buf_row = buf->bits + (y * buf_bytes_per_line);
        ximg_row = (void *)ximg->data + (y * ximg->bytes_per_line);

        /*
         * we don't want to copy any extra XImage row padding
         * so we just copy up to image width instead of bytes_per_line
         */
        memcpy(buf_row, ximg_row, ximg->width * ximg_bytes_per_pixel);
        for (int i = 0; i < ximg->ximg_bytes_per_pixel; i += 4)
        {
            buf_row[i + 0] = ximg_row[i + 2];
            buf_row[i + 1] = ximg_row[i + 1];
            buf_row[i + 2] = ximg_row[i + 0];
            buf_row[i + 3] = ximg_row[i + 3];
        }
    }`

The above changes are invalid, a lot of black lines appear abnormally, I do n’t know what is wrong, and finally I found that Android hides BGRA
SurfaceHolder holder = surfaceview.getHolder ();
         holder.setFormat (5);
This setting solves the problem
