### ISSUE TITLE
Debian screen occasionally displays on phone display instead of HDMI display

### ISSUE THREAD

**Issue by lhitc** [maruos/maruos#15]
Since I installed maru yesterday, I had it about 4-5 times that the Debian screen appeared at the top half of the phone's display.
Phone display is in portrait mode, Debian screen is cut off on the right side.
The HDMI monitor stayed in standby mode in most of these cases, except for one time when it woke up but still did not display anything.
HDMI monitor is a Samsung 24" with 1920x1200 resolution.
Unfortunately, I don't know how to reliably reproduce it.

**Comment by pdsouza** [comment]
Thank you for the report! This is a known issue with unstable HDMI links, see [this forum post]( https://groups.google.com/forum/#!topic/maru-os/64p3cShm7Mw).

**Comment by pdsouza** [comment]
Closed in https://github.com/maruos/mflinger/commit/4e4b0d96e24827b2d83fbb2e98e37c19726a5ccc.
