### ISSUE TITLE
Desktop freeze possible resolution

### ISSUE THREAD

**Issue by dianaxxyyzz** [maruos/maruos#159]
If your linux instance starts so you configured the kernel to suport lxc to start it , but you seee anomalies inside linux , make sure your kernel configs are like in '<' and not like in '>'

```
< CONFIG_SYSVIPC_SYSCTL=y

< # CONFIG_MEMCG is not set

> CONFIG_MEMCG=y

< # CONFIG_BLK_CGROUP is not set

> CONFIG_BLK_CGROUP=y

< CONFIG_IPC_NS=y


< CONFIG_SYSVIPC_COMPAT=y

< CONFIG_DEVTMPFS=y
< # CONFIG_DEVTMPFS_MOUNT is not set

> # CONFIG_DEVTMPFS is not set

< CONFIG_DEVPTS_MULTIPLE_INSTANCES=y

< CONFIG_AUTOFS4_FS=y

> # CONFIG_AUTOFS4_FS is not set
```

**Comment by utzcoz** [comment]
@dianaxxyyzz @pdsouza could we add this solution to doc? The developer may check the doc firstly when he/she has the similar problem.

**Comment by pdsouza** [comment]
Added in https://github.com/maruos/maruos/commit/15760b24cfc0f2633c8f793eed9c5725430dd7bc.

**Comment by utzcoz** [comment]
> Added in [15760b2](https://github.com/maruos/maruos/commit/15760b24cfc0f2633c8f793eed9c5725430dd7bc).

Could we close this issue?
