### ISSUE TITLE
Flashlight stops after 30 seconds

### ISSUE THREAD

**Issue by Ezerbeth** [maruos/maruos#16]
Hi,

I have a problem with the flashlight. It stops working after 30 seconds, and the only way to get it working again is to reboot the phone. I use it quite a lot so this is a major issue for me, I assume others as well.

I can replicate 90% of the time. Unlock screen (but not the phone), pull top menu down, start flashlight from top menu, close screen, wait. The icon stays selected, but the light is off. Clicking the icon again does nothing. After reboot, all is well again.

Let me know if you need logs or whatnot. 

Thanks

P.S. Great work!

**Comment by pdsouza** [comment]
Thank you for the detailed report!

I tried to replicate this exactly according to your instructions, but my flashlight stays on after 30 seconds...seemingly indefinitely. Is there anything I'm missing? Are you connected over HDMI while doing this (assuming not since you are closing the screen explicitly)? I'll try a few more times randomly to see if I can replicate.

**Comment by Ezerbeth** [comment]
Hi,

I'm ashamed to say I have yet to try the HDMI part, still waiting for the adapter haha.

I figured I'd be smart about it, and connect it through ADB then logcat it, and provide the log while it happens... try as I might, it won't do it while it's connected on my Mac.

Disconnect it, try and tada! Happens within 20 seconds. Unfortunately I can't really provide a log through logcat.

I also noticed when it happens, the camera stops as well. "Camera error. Can't connect to the camera."

I'll try to re-flash this weekend if you can't replicate it, just to eliminate that possibility.

Thanks!

**Comment by Ezerbeth** [comment]
Also for clarification, I flashed the gapps from the readme, and installed TWRP. Just in case that might come into play. I also encrypted Android.

**Comment by Ezerbeth** [comment]
Ok I just noticed, if you unlock the phone and pull the top menu, it doesn't happen. Maybe I wasn't super clear originally.

- Phone is powered on in my pocket, freshly booted
- I press the power button to see the screen, but don't enter my PIN
- Pull the dropdown menu, turn flash light
- Wait and it stops, bringing down the camera

But if I do this, then it doesn't happen:
- Phone is powered on in my pocket, freshly booted
- I press the power button to see the screen, but DO enter my PIN unlocking the device
- Pull the dropdown menu, turn flash light
- Wait forever and it never happens.

Hopefully that clears it up, and I know how to use it for now. Sorry for the spam!

**Comment by Ezerbeth** [comment]
Ok I've reflashed and I can't reproduce this anymore.

**Comment by pdsouza** [comment]
Thank you for working through this! Glad to hear it's working now. But I have a suspicion that this may be caused by encryption since you can only reproduce this without entering your PIN.
