### ISSUE TITLE
Maru desktop won't load after encryption

### ISSUE THREAD

**Issue by Ezerbeth** [maruos/maruos#17]
Hi again!

After a clean flash, TWRP + gapps and encryption, I get a black screen when connecting my display. I tested this a couple of times and it all works well until I encrypt the device. When I manually try to enable it from the dashboard setting, it says Maru desktop failed to start.

Hopefully this one is easily reproducible on your end, or even a known issue; I checked the FAQ and forums and couldn't find anything.

Thanks!

**Comment by pdsouza** [comment]
Thank you for noting this! This is a known issue and I forgot to add this to an obvious area like the FAQ yet, my bad. Sorry you had to spend time on flashing this several times. It's on there now: https://github.com/maruos/maruos/wiki/FAQ#i-encrypted-my-device-and-now-maru-desktop-fails-to-start-whats-going-on

**Comment by lotherk** [comment]
Hi @pdsouza, can you tell us a little bit more about why this is not working with encryption or what has to be done to make it work? I'd really like to use maruos but am really concerned using it as a desktop without encryption - or is it possible to create an encrypted image which will be mounted for /home (for example?) so at least the user data is encrypted?

**Comment by pdsouza** [comment]
@lotherk Thanks for bumping this, this slipped off my radar! This is just me being lazy and not making Maru's system services encryption-aware, i.e. they try to start before decryption is complete and cause errors. I'm looking into this next.

**Comment by pdsouza** [comment]
Fixed in https://github.com/maruos/vendor_maruos/commit/c760cb5e184e7c9020b3330a544e12103fd20b1e. This will be available in the next release!

**Comment by pdsouza** [comment]
Going to keep this issue open till the next release to remind myself to update the corresponding FAQ.

**Comment by Ezerbeth** [comment]
Sorry to bump this. But can you deactivate/remove the option until this is solved? Third friend that bricks it because no one reads the FAQ. Thanks.

**Comment by pdsouza** [comment]
Updated FAQ. Please upgrade to v0.4 to encrypt both mobile and desktop!
