### ISSUE TITLE
Some udpates for user guide contents

### ISSUE THREAD

**Issue by utzcoz** [maruos/maruos#173]
1. Some newer devices doesn't have `recovery` partition, and we should add doc to guide user to flash `boot ` partition.
2. Some devices will enter `No command` page with broken Android robot icon after running `adb reboot recovery`, we should add guide how to pass it to enter real recovery page.
3. When flashing images with `TWRP`, we should tell user to disable signature checking before flashing. Our built doesn't have the same signature as official images.

Those are obsolete user guide contents I found now, and I will send a PR to update it.

cc @pdsouza.

**Comment by pdsouza** [comment]
Thanks for documenting this and working on fixing these issues. There is a lot we can do to improve the docs.
