### ISSUE TITLE
Please add support for MI 10T

### ISSUE THREAD

**Issue by Saikatsaha1996** [maruos/maruos#174]
I really loving Maru os
Please add support 

Device Mi 10T
Android 11
Processor Snapdragon 865
Ram DDR5
Gpu Adreno 650

Please help wanted

**Comment by utzcoz** [comment]
Thank for your love of MaruOS. The support for new device should be done by developer has this device. I think all current maintainers don't have this device. The MaruOS doesn't support Android 11 now, I think it is difficult to support.

**Comment by Saikatsaha1996** [comment]
Not a problem I can downgrade my os to 10...

**Comment by utzcoz** [comment]
Sorry, the official MaruOS maybe stay on Android 9 version some months. You can post your need to https://groups.google.com/g/maru-os to check whether there are other developers have interested on porting MaruOS for MI 10T based on community Android 10 version MaruOS.

**Comment by utzcoz** [comment]
If anyone has interesting in porting MaurOS for Mi 10T, you can follow https://maruos.com/docs/developer/#structure for it. If you have question about porting, you can create a new discussion at this repo for it. Feel free to reopen this issue if you have problem.
