### ISSUE TITLE
How to permit socket connection between android (host) and container(Linux)?

### ISSUE THREAD

**Issue by dlan17** [maruos/maruos#182]
Hi Maruos Developer:
   FYI, I'm trying to port mflinger/mclient to android 11.. while having problem here

   Do you know how to permit socket connection between Android OS and the container(Linux)?
as I understand the mflinger running at android act as server, while mclient running at container(Linux) act as client, and it will connect to mflinger.
   Following is the error while running mclient, it fail at sock connection, any idea?

Aug 20 05:32:37 stretch systemd[1]: Started mflinger client for X11.
Aug 20 05:32:37 stretch mclient[62]: error connecting socket: Connection refused
Aug 20 05:32:37 stretch mclient[62]: error calling MOpenDisplay
Aug 20 05:32:37 stretch systemd[1]: maru-mflinger-client.service: Main process exited, code=exited, status=255/n/a

**Comment by utzcoz** [comment]
Hi @dlan17 , it's very happy to see MaruOS is on the road to Android 11. In MaruOS, mclient in Linux container uses `AF_UNIX` socket to communicate with mflinger in Android. It hopes to work correctly. If it doesn't work correctly, there are some possible reasons:
1. Missed related SELinux rules to permit it.  We have added many SELinux rules for MaruOS, but new devices and new Android  maybe need more rules. For example, I should add new rule to allow perspectived to read gpu device when porting MaruOS 0.7 for pixel 3a(https://github.com/maruos/vendor_maruos/commit/d27ea10d9b7c263be4f5ce90195afd7181cc75bf). There is an [official document](https://source.android.com/security/selinux/customize?hl=zh-cn) to show how to customize SELinux rules for Android.
2. Incomplete LXC config for network. I can ensure current LXC  config for network can work correctly for Android 8 and Android 9. You can use the following commands to check whether Linux can connect Android network group(your Android should has network):
```shell
adb root
adb shell
lxc-start --name default  // default password is maru
sudo apt update
sudo apt upgrade
```  
It it can fetch updates from network, the network config of LXC maybe is correct. If not, maybe there is incomplete LXC config for network.

In my perspective, the first reason has a greater possibility than second.

**Comment by dlan17** [comment]
hi @utzcoz 
 Thanks for your quick response!
 It seems there is problem with network in container, since I've already tried to force disable SE rules (set to permissive mode)..
 So, how to setup the network in container? as I check maruos which uinsg "lxc.network.type = none" for container (file /data/maru/containers/default/config)?

**Comment by utzcoz** [comment]
> as I check maruos which uinsg "lxc.network.type = none" for container (file /data/maru/containers/default/config)?

What I said above is it. I read [lxc.conf](https://linux.die.net/man/5/lxc.conf) again, I think `lxc.network.type = none` is fine, and it will let container to share host's network without any bridge, if you don't use newer lxc. Could you provide a full logcat when starting Linux on MaruOS? Maybe there is something can be used to identify problems. And another thing, could you help to check network connection in container ? I think normal `ping` command is enough.

**Comment by dlan17** [comment]
forgot to report back, use "lxc.net.0.type = none" fix my problem (which share host's network space)

**Comment by utzcoz** [comment]
> forgot to report back, use "lxc.net.0.type = none" fix my problem (which share host's network space)

Hi @dlan17 , thank you to give feedback about this problem. Do you have willing to send a PR to https://github.com/maruos/maruos/blob/master/docs/developer/porting.md to add a short description for this problem? Maybe there are other developers could meet this problem.

**Comment by dlan17** [comment]
Em.. I haven't investigated further, but the root cause is probably that I upgrade lxc to more recent version 4.0.10 (still haven't ported it android, but by throw a static app)

**Comment by utzcoz** [comment]
> Em.. I haven't investigated further, but the root cause is probably that I upgrade lxc to more recent version 4.0.10 (still haven't ported it android, but by throw a static app)

NP. Looking forward to hearing you good news to upgrade lxc to 4.x correctly.
