### ISSUE TITLE
There are many files...! Which one should I download?

### ISSUE THREAD

**Issue by Soumyadeep98O** [maruos/maruos#185]
![Screenshot 2021-12-07 172844](https://user-images.githubusercontent.com/30073064/145025324-f614ce59-3a77-4b16-819a-14dcb437da02.png)
 And also, does this OS support Redmi 5? Redmi 5 is a very good capable device, after its initial release the device is still capable of supporting latest Android, and the XDA community is very active of Redmi 5 (Rosy), so can you release support for this device too? Pls!

**Comment by utzcoz** [comment]
Sorry, MaruOS doesn't support Redmi 5 now. If you want to download files for Redmi 5, there are no files for you.

**Comment by utzcoz** [comment]
The supporting for new device is created by community volunteer/developer, and current developers of MaruOS don't have Redmi 5 device to make porting. If you have this device, it's recommended to port it by yourself.

**Comment by Soumyadeep98O** [comment]
Oh! BTW, can you tell me where to learn about porting and stuff?

**Comment by utzcoz** [comment]
You can check our developer doc: https://maruos.com/docs/developer/#structure. If you have any problem about porting, you can create a new discussion at this repo.

**Comment by Soumyadeep98O** [comment]
Ok, I'll try!
Thnx!

**Comment by utzcoz** [comment]
> Ok, I'll try! Thnx!

We're really encourage other developers to port MaruOS to different devices. Feel free to ask questions for your problem at this repo's GitHub Discussion.
