### ISSUE TITLE
Add a MobilePhone View

### ISSUE THREAD

**Issue by supertobi** [maruos/maruos#2]
The MOTOROLA ATRIX hat a nice "Mobile View" where it was possible to use the connected phone apps:
https://motorola-global-portal.custhelp.com/app/answers/detail/a_id/62708/session/L2F2LzEvdGltZS8xNDY1NDgxODgwL3NpZC94STVEWENTbQ%3D%3D

You can find the sourcecode here:
https://sourceforge.net/motorola/motorola-webtop/news/2011/09/announcing-the-new-motorola-webtop-source-project/

**Comment by twaik** [comment]
As an option scrcpy can be used for this...

**Comment by twaik** [comment]
I think this issue can be closed...

**Comment by utzcoz** [comment]
@supertobi you can try scrcpy. Thanks @twaik .

**Comment by twaik** [comment]
@utzcoz I think you can try to modify scrcpy to make it work without adb. I think it will be helpful feature.

**Comment by utzcoz** [comment]
> @utzcoz I think you can try to modify scrcpy to make it work without adb. I think it will be helpful feature.

I have did similar things for multi-display Android device, and I will mark it as another queuing feature for MaruOS. Thanks @twaik .
