### ISSUE TITLE
root for maruos

### ISSUE THREAD

**Issue by HKTangyuan** [maruos/maruos#206]
我该如何在maruos上获取root权限

**Comment by utzcoz** [comment]
@HKTangyuan 你可以在刷机的时候主动刷上 TWRP，然后通过设置获取 root 权限。

You can install TWRP when flashing MaruOS to your device, and you can enable root from official Settings app.

**Comment by HKTangyuan** [comment]
十分感谢，希望maruos能够支持运行docker，更好地发挥linux的能力，但这需要内核配置的支持
Thank you very much. I hope maruos can support running docker and make better use of Linux, but this requires the support of kernel configuration.
