### ISSUE TITLE
ssh access to my maruos

### ISSUE THREAD

**Issue by MangoCats** [maruos/maruos#22]
Hi,

I have been able to sudo apt-get install openssh-server, and run ssh-keygen, but I cannot get a connection to my maruos via ssh from other machines in my network.  I can see my maruos' ip address on my router, but with the ip command I'm only seeing ip6 addresses - does maru support ip4 addresses?

**Comment by MangoCats** [comment]
o.k. so with ip a I get the same address shown as on my router, but still "connection refused" when trying to scp something in or just ssh login as maru@maruipaddress

**Comment by MangoCats** [comment]
so 'sudo service ssh restart' got it going - I'm not used to having to kick it off, though, usually installing it will also make the server launch at boot...

**Comment by pdsouza** [comment]
Maru OS supports SSH out of the box but it is disabled by default for security--that's probably why your server didn't kick off. From a fresh install, all you need to do is enable and start the ssh service. See https://groups.google.com/d/msg/maru-os/wihyWxTklO0/8YldSglbCgAJ.

**Comment by pdsouza** [comment]
By the way, SSH is enabled by default from Maru OS v0.3 and up!

**Comment by curiousercreative** [comment]
This is terrific feature to have enabled by default! For those interested, you'll be connecting to the IP host device IP address and it seems to forward ssh connections to Debian. I've only had luck connecting while on the same local network. Here's a step-by-step to connect via ssh:
1. Determine your phone's IP address. Settings > About Phone > Status > IP address. On my local network, my phone's IP address is `10.0.0.10`.
1. In an ssh client on the same network (could be your phone) `ssh maru@10.0.0.10` and enter `maru` as the password.
1. If prompted to trust the certificate provided, enter `y`

And if you're interested in this feature, you might also be interested in connecting via VNC.
1. Install a VNC server: `sudo apt-get install x11vnc`
1. Run the server and protect it with a password that you supply: `x11vnc -forever -display :0 -usepw`
1. In a VNC client (could be your phone) connect to the phone's IP address with the password supplied.
 
@pdsouza, I think both connecting via SSH and VNC would be great additions to the wiki/FAQ :)

**Comment by pdsouza** [comment]
@curiousercreative Added to [wiki](https://github.com/maruos/maruos/wiki/Tips) and [FAQ](https://github.com/maruos/maruos/wiki/FAQ#can-i-use-maru-desktop-without-an-hdmi-monitor-around)--thank you for the excellent walkthrough!

**Comment by curiousercreative** [comment]
@pdsouza is there any train to keep this issue open? Seems like it's been resolved!

**Comment by pdsouza** [comment]
@curiousercreative Thanks for the reminder, I need to do a better job at keeping our issues clean! Closing.

**Comment by curiousercreative** [comment]
@pdsouza happy to help by flagging ones I see for you!

**Comment by regular** [comment]
I just installed maru 0.4 and get `Port 22: Connection refused`. Did you change this in the latest release? Or is sshd still supposed to be on by default?

**Comment by regular** [comment]
Ok, just found #76

**Comment by pdsouza** [comment]
@regular #76 has not been released yet so sshd should be on by default still
