### ISSUE TITLE
Samsung S10 G973F

### ISSUE THREAD

**Issue by unknown1818** [maruos/maruos#220]
Hi, 

I would love to have a maruos linux on s10, can i install s9 maruos starlte version? Ihave twrp etc and i can test on my phone.

Best regards

**Comment by utzcoz** [comment]
@unknown1818 Sorry, I think it can't. Current MaruOS dependens on firmware of specific devices, and I think they are different between s10 and s9. It might needs other contributors to port MaruOS for s10.
