### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by junocomp** [maruos/maruos#225]
Hi, I was wondering if the project is dead. There has not been a release since 2017.

If is not dead, which Android version is it running. 

Thanks,

**Comment by luka177** [comment]
Hi, this project is not dead rather frozen imo. Last android version was 9, but it is rather easy to pick changes on newer versions if there is any interest in that.

**Comment by pdsouza** [comment]
We are most certainly not dead! We are working on bringing Maru to more recent versions of Android. We hope to have some announcements about this before too long.

And as always, if you are interested in the project we are happy to have your contributions.

Feel free to re-open if you have further questions.
