### ISSUE TITLE
No Google Play store with Linux Installer Script

### ISSUE THREAD

**Issue by irishman2020** [maruos/maruos#23]
Using the linux installer script, I got maru working fine in my nexus 5. The play store was not preinstalled. There are no instructions on how to install it either. Since I did not use twrp, how can I sideload the google apps?

**Comment by ConorIA** [comment]
The instructions are posted on the Maru forum. Stickied right at the top.

**Comment by irishman2020** [comment]
Thank you, i finally found a link to the forums on the very bottom of the Maru OS main site. Can someone add a link to the stickied forums in the installation guide or the FAQ? This seems like a small oversight.

**Comment by pdsouza** [comment]
Thanks for bringing this up. Added to the FAQ: https://github.com/maruos/maruos/wiki/FAQ#how-can-i-get-access-to-the-play-store-on-maru-os.

**Comment by Ezerbeth** [comment]
It's also included in HELP.txt inside the package, that's how I found it.

**Comment by pdsouza** [comment]
Closing since we have deprecated the installers as of Maru 0.6 in favor of flashable zips.
