### ISSUE TITLE
MaruOS on Nexus 5X?

### ISSUE THREAD

**Issue by airobert** [maruos/maruos#26]
I am not sure if MaruOS will also run for Nexus 5X. Looks there isn't much difference. Has anyone tried yet?

Thanks!

**Comment by pdsouza** [comment]
Hi airobert, this release is only for Nexus 5. Please do not try to install this on your 5X! Some more information is available in the [FAQ](https://github.com/maruos/maruos/wiki/FAQ#which-devices-are-officially-supported).

The 5X lacks HDMI support so will have to wait till Maru OS offers a workaround for that.

**Comment by pdsouza** [comment]
Update: a 5X port is in progress! https://groups.google.com/d/msg/maru-os-dev/YufKu3w2xkQ/9qPEp9EiAQAJ

I'll update here as we get some alpha/beta builds up.

**Comment by igoralmeida** [comment]
Nice! Any plans to attack the lack of slimport?

On January 12, 2017 6:53:15 PM GMT-02:00, pdsouza <notifications@github.com> wrote:
>Update: a 5X port is in progress!
>https://groups.google.com/d/msg/maru-os-dev/YufKu3w2xkQ/9qPEp9EiAQAJ
>
>I'll update here as we get some alpha/beta builds up.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/maruos/maruos/issues/26#issuecomment-272280162

-- 
Igor Almeida (móvel)

**Comment by pdsouza** [comment]
@igoralmeida Wireless streaming in the works! 

For anyone else interested, follow along here for early builds and stuff: https://groups.google.com/forum/#!topic/maru-os-dev/U9EpPQ0SFb0

**Comment by ffischer1984** [comment]
Hi,
is an easy installer planned for the nexus 5x??

**Comment by pdsouza** [comment]
@ffischer1984 Yes! As soon as we have an official build for the 5X I will make sure to ship an easy installer along with the update zip.

**Comment by pdsouza** [comment]
Nexus 5X is an official device for Maru as of our recent 0.6 release! You can find builds on our website: https://maruos.com/downloads/.
