### ISSUE TITLE
In Android you can use the Debian command it?

### ISSUE THREAD

**Issue by soarteam** [maruos/maruos#35]
In Android you can use the Debian command it?
apt-get? etc.

**Comment by soarteam** [comment]
If you can, I will be able to handle the task at any time.
busybox not strong.

**Comment by Ezerbeth** [comment]
Not directly but you can SSH into it from an ssh client on the phone.

I agree this would be a cool feature, a built-in app that allows you to get a direct terminal inside Linux.

**Comment by soarteam** [comment]
root@localhost:22
Connect to Android's SSH?

**Comment by Ezerbeth** [comment]
maru@localhost:22 unless you enabled root logins in sshd_config in Linux, I think they're disabled by default. You can then "sudo su -" to switch to root.

**Comment by Ezerbeth** [comment]
You can also SSH into the device using its LAN IP from any computer, as long as it's on the same network.

**Comment by soarteam** [comment]
Nice, So Cool

**Comment by ahstro** [comment]
I'm not familiar with how Maru works (don't have a Nexus, waiting for some ports and to be able to justify buying a new phone), but would a `chroot` be possible? Does BusyBox even contain `chroot`?

**Comment by soarteam** [comment]
Yes
root@hammerhead:/ # chroot
usage: chroot NEWPATH [commandline...]
 
Run command within a new root directory. If no command, run /bin/sh.
 
chroot: Needs 1 argument

**Comment by Ezerbeth** [comment]
I also thought about that, but I can't see the partition in df. Not exactly sure how Linux is booted, waiting for it to become open sourced.

**Comment by soarteam** [comment]
Chroot is a good choice. Just do not know can not.

**Comment by chevdroid** [comment]
@Ezerbeth all the Maru OS code is already in GitHub so it is already open sourced. See here the post in google groups:

https://groups.google.com/forum/#!topic/maru-os-dev/Td2THWjJRT0

**Comment by soarteam** [comment]
Can automatically mount USB?

**Comment by soarteam** [comment]
@Ezerbeth I do not have HDMI device.
Now I can not connect.

**Comment by Ezerbeth** [comment]
Maru won't boot until it detects an HDMI display connected, so you can't access it until then.

**Comment by soarteam** [comment]
@pdsouza We are hoping to solve.

**Comment by soarteam** [comment]
Provide a version MINIMAL
Only Shell. Develop anywhere.
Can still HDMI.

**Comment by chevdroid** [comment]
As far as I know there is already a feature request/planned function to let debian boot without hdmi connection.

For you USB mount question, since you need to use a slimport adapter, your USB port is used, when Debian is running and I don't know any adapter which is working with Slimport and USB-OTG simultaneously.

**Comment by pdsouza** [comment]
See #5 for launching the desktop without HDMI.

**Comment by pdsouza** [comment]
Maru OS supports using the desktop without HDMI as of v0.3, see https://github.com/maruos/maruos/issues/5 for more details.

Closing this.
