### ISSUE TITLE
Support for LG G2.

### ISSUE THREAD

**Issue by suhail-sullad** [maruos/maruos#37]
Hi,

Want to tryout MARUOS. However have a small question regarding support 
as nexus 5 and lg g2 are built on same specification and manufacturer. MARUOS for nexus 5 should be portable with LG G2 aswell?

**Comment by chevdroid** [comment]
Yes it is! It's already planned to port it to the LG G2.

Please look at this google groups thread:
https://groups.google.com/forum/#!topic/maru-os-dev/YufKu3w2xkQ

**Comment by montvid** [comment]
Any luck porting maruos to lg g2?

**Comment by utzcoz** [comment]
If anyone has interesting in porting MaurOS for LG G2, you can follow https://maruos.com/docs/developer/#structure for it. If you have question about porting, you can create a new discussion at this repo for it. Feel free to reopen this issue if you have problem.
