### ISSUE TITLE
VGA?

### ISSUE THREAD

**Issue by sixtyfive** [maruos/maruos#44]
I just bought a Nexus 5 to install Maru on, which worked just fine with the install script you provide. Unfortunately I discovered that all screens I have or that my friends have as well as all the projectors at university are either VGA or DVI. If I buy one of the SlimPort-to-VGA adapters that are available on Amazon, etc. (e.g. https://www.amazon.de/CAMAC-SlimPort-Micro-Adapter-Optimus/dp/B012ZZ5912/ref=sr_1_1?ie=UTF8&qid=1475281630&sr=8-1&keywords=slimport+vga), will that work with Maru?

**Comment by pdsouza** [comment]
Thanks for trying out Maru!

I haven't tried VGA/DVI adapters myself (I develop Maru OS with straight HDMI), but apparently a user has had luck with a DVI adapter: https://groups.google.com/d/msg/maru-os/ErXDE6g4zSQ/snVe6kSwBgAJ. Please search the forum for "VGA" or "DVI" to read up about other user experiences before you decide to make an investment in that adapter.

A lot of this is dependent on the adapter and monitor itself, and at the end of the day you might have to experiment. If you end up getting the adapter, please let the community know on the forum whether it worked for you or not.

**Comment by sixtyfive** [comment]
Thank you for the quick answer! So the person on the forum used two adapters in a row and from the conversation there it seems like neither the phone nor the displays have any problem with that, but that it can be a problem if the displays can't go to Full HD, which sort-of makes sense. The only two other threads I found that mention VGA (https://groups.google.com/forum/#!searchin/maru-os/vga|sort:relevance/maru-os/YexPDVojqgI/MEfKEHEWBwAJ, https://groups.google.com/forum/#!searchin/maru-os/vga|sort:relevance/maru-os/o9BpnXVK3hg/P_nSq7ScBwAJ) read to me like the problem is always resolution, and never signal transmission. The person there uses two separate adapters though, which seems like a good idea, so I'll try it that way.

The usefulness of something like Maru OS hinges on it being usable in as many places and as many unforeseen circumstances as possible, so it would be cool if https://github.com/maruos/maruos/issues/19 got some more attention ;)

One more question: in one of the mentioned threads from March you said that under good circumstances a Marshmallow-based Maru could be as close as April. That didn't happen though, so did you hit some roadblock there?

**Comment by pdsouza** [comment]
I have realized the folly of forward-looking statements... However, master has been on Marshmallow for a while now and will be available in the next release: https://github.com/maruos/maruos/issues/6.

**Comment by sixtyfive** [comment]
Nicely put! FWIW, forward-looking statements are easier to make for a group of people than for a single person (see e.g. bigger projects' 6-month release cycles). Since yesterday evening I've been setting up Maru with a mix of stuff taken from F-Droid & Aptoide (between the two of them, you can find almost everything) and have been amazed at the speed and battery life of the combination of Nexus 5 and Maru OS. Well, perhaps that's not too hard when you're coming from a Galaxy S1 running Marshmallow. The only thing I'm really missing is the ability to selectively allow or deny permissions that Marshmallow introduces. Anyways, it'll be a couple of days before the adapters will arrive in the mail and then I'll give word on whether they work.

**Comment by sixtyfive** [comment]
Hi @pdsouza, so the adapters just arrived. The bad news is: it doesn't work with either screen nor projector. The good news is: both keep flashing and keep trying to display something. The screen probably in its native 1680x1050, the projector for some reason only in 1280x1024. Based on how it looks I'm pretty convinced now that the hardware side is basically fine and it's only about the resolution. Like I suggested in #19, a list of resolutions to manually select from would be very helpful. I'll close this issue as a duplicate.

(For reference, the USB-Slimport-to-HDMI adapter is a [Cable Matters 603001](https://www.amazon.com/Cable-Matters-Micro-SlimPort-Charging/dp/B00HFYLR4M/ref=sr_1_2?s=electronics&ie=UTF8&qid=1475829205&sr=1-2&keywords=cable+matters+slimport+hdmi) and the Active-HDMI-to-VGA adapter is a [Cable Matters 113046](https://www.amazon.com/Cable-Matters-Active-Adapter-Micro-USB/dp/B00879DM56/ref=sr_1_1?s=electronics&ie=UTF8&qid=1475829248&sr=1-1&keywords=cable+matters+hdmi+vga).)

**Comment by pdsouza** [comment]
Thanks for the report! 

Added some more info to #19 on supported resolutions. Turns out that the hammerhead driver only supports [standard HDMI timings](https://en.wikipedia.org/wiki/Uncompressed_video#HDMI_Specifications), and 1680x1050 and 1280x1024 aren't on that spec. Add multiple adapters to the mix and things can get weirder due to timing issues.
