### ISSUE TITLE
Any chance of porting this to the Nexus 4

### ISSUE THREAD

**Issue by snacdaws** [maruos/maruos#48]
just decided to give my Nexus 5 to a family member as their first phone and revived my Nexus 4 after 2 years after i broke it's screen and was hoping for a port of MaruOS 

would be happy to help test it out if someone does port it to the Nexus 4

**Comment by pdsouza** [comment]
Good to hear from you again @snacdaws! Someone's signed up for the Nexus 4 on the device port thread: https://groups.google.com/forum/#!topic/maru-os-dev/YufKu3w2xkQ but no updates so far. I'll pester him for some info on what's going on!

**Comment by pdsouza** [comment]
I checked up with him and it looks like he doesn't have the N4 anymore but is trying to get a new one soon. 

If anyone else would like to try porting to the N4 please see the [Porting Guide](https://github.com/maruos/maruos/wiki/Porting-Guide)

**Comment by snacdaws** [comment]
Cool can't wait

**Comment by utzcoz** [comment]
If anyone has interesting in porting MaurOS for N4, you can follow https://maruos.com/docs/developer/#structure for it. If you have question about porting, you can create a new discussion at this repo for it. Feel free to reopen this issue if you have problem.
