### ISSUE TITLE
[Question] Port to Xiaomi

### ISSUE THREAD

**Issue by efargas** [maruos/maruos#49]
MaruOS is build from AOSP, it can be build from MIUI to support Xiomi devices?
I have a Xiaomi Redmi Note 3 with Mediatek Helio X10.
The Pro version has Snap Dragon 650.

**Comment by pdsouza** [comment]
Please see device port thread for ports in progress: https://groups.google.com/d/msg/maru-os-dev/YufKu3w2xkQ/9qPEp9EiAQAJ

With some luck, we'll get someone with a Xiaomi help to port. Our focus is on Nexus devices at the moment though.

**Comment by utzcoz** [comment]
If anyone has interesting in porting MaurOS for Xiaomi Redmi Note 3, you can follow https://maruos.com/docs/developer/#structure for it. If you have question about porting, you can create a new discussion at this repo for it. Feel free to reopen this issue if you have problem.
