### ISSUE TITLE
Launch Maru Desktop non-interactively without HDMI display

### ISSUE THREAD

**Issue by pdsouza** [maruos/maruos#5]
It makes sense to allow users to launch Maru Desktop without an HDMI display non-interactively in case they are running start-up script jobs or controlling the system with SSH or VNC.

Here are some feature request threads:
https://groups.google.com/forum/#!topic/maru-os/dnBDTXwvehc
https://groups.google.com/d/msg/maru-os/qQ77tj3cbmE/Kg-kd2TPQQAJ

**Comment by snacdaws** [comment]
hopefully this works soon

**Comment by optio** [comment]
Would be great if we could use a Chromecast to connect the display, not needing any HDMI cables on the phone!

**Comment by lhitc** [comment]
+1!
A full-featured headless Debian server for development or demonstration purposes would really be great.

**Comment by Asynchronous003** [comment]
+1 hope to change repo to Kali rolling :)

**Comment by alex2844** [comment]
+1

**Comment by pdsouza** [comment]
Closed in:
* https://github.com/maruos/android_platform_packages_apps_Settings/commit/cabc07fe7a76f67e25510ead7aba022f5f45d4cf
* https://github.com/maruos/blueprints/commit/edbfe13dc0a78769cb42ab9f1cb8dac3dd7933a4

ssh is enabled by default in the desktop now, so you can just start up Maru Desktop whenever you want and ssh in to configure stuff if you don't have an HDMI display or cable around. 

As @lhitc mentioned, pretty cool to carry around a full-features headless Debian server in your pocket! This will be available in the next release. Yay!

**Comment by idpnd** [comment]
What about VNCing/X11ing into the desktop from phone to use linux apps on phone screen? It does make sense ;)

**Comment by pdsouza** [comment]
VNC works great with Maru OS! See this comment: https://github.com/maruos/maruos/issues/28#issuecomment-237997620

**Comment by soarteam** [comment]
So Cool
