### ISSUE TITLE
Can't download any file on android

### ISSUE THREAD

**Issue by ppjuarez** [maruos/maruos#52]
Whenever I try to download a file via web browser or email, the app crashes and doesn't download a thing.

Already tried to wiping everything, issue persists.

**Comment by pdsouza** [comment]
Hi, thanks for reporting this issue -- I totally missed this during my testing, nice catch!

It looks like the stock Browser app does not have permission to access storage by default, thus your downloads fail.

You can change this by toggling the permission to access storage under Settings > Apps > Browser > Permissions > Storage. Please give this a try and your downloads should work again.

I will keep this issue open to see if I can enable this permission by default!

**Comment by ppjuarez** [comment]
Thanks for the quick answer, that fixed it.

**Comment by pdsouza** [comment]
Keeping this open for others who run into this and to remind myself to figure out how to make this permission enabled by default.

**Comment by pdsouza** [comment]
Fixed in https://github.com/maruos/android_platform_frameworks_base/commit/bf4a65ee8ba2c7dfdcc181d96ddf1c1a26a9b83c. This will be available in the next release.

**Comment by pdsouza** [comment]
Fix was released in v0.4, please upgrade!
