### ISSUE TITLE
Installing apk fails

### ISSUE THREAD

**Issue by wjrivera** [maruos/maruos#55]
Is it possible to install apks in Maru? I've have unknown sources option picked, and the files just won't open.  Is there any other options for installing non-google app stores?
Thank you

**Comment by pdsouza** [comment]
Can you give me steps to reproduce?

I tried installing [F-Droid](https://f-droid.org/) and I was able to install it fine after selecting the "Unknown sources" option in settings.

**Comment by wjrivera** [comment]
Nexus 5 32GB
Went to https://f-droid.org/, browser crashed when clicked on Download F-Droid.
Then hooked up the phone to my computer, transferred the F-Droid apk to the phone.
Open the apk and I get the error of Cannot open file.

**Comment by pdsouza** [comment]
See #52 to fix the browser crash. You need to give permission to the
browser to download files. Sorry for confusion, that permission should be
there by default.

**Comment by wjrivera** [comment]
Thank you so much!  Awesome!
