### ISSUE TITLE
Sim Card not available still showing in airplane mode

### ISSUE THREAD

**Issue by ahalbrock** [maruos/maruos#57]
If I put phone into airplane mode, the "lack of simcard" indicator at the top goes away as I'd expect, when after rebooting the phone, airplane mode is still on but the indicator is back, I have to turn airplane mode off and on again to have the indicator go away.

Using V.3 Marshmallow

**Comment by pdsouza** [comment]
This is resolved in Maru 0.6. Please upgrade!
