### ISSUE TITLE
MaruOS on Marshmallow

### ISSUE THREAD

**Issue by arrmo** [maruos/maruos#6]
Hi,

Not really an issue, but a question - is there any way to have MaruOS on Marshmallow (Android 6.0.1)? I have this on my phone now, and it really helps battery life -> don't really want to give that up.

Thanks!

**Comment by pdsouza** [comment]
Definitely possible, question is really just when :). I'm trying to get all the repos organized to get the open source project off the ground, but after that I'll see what I can do!

As a workaround for now, you can use Maru OS as a secondary ROM in MultiROM, with Marshmallow as your primary ROM. See [this forum post](https://groups.google.com/forum/#!msg/maru-os/TGCHBXxW45c/RdpU3a3CCQAJ) for more details on getting this to work.

**Comment by arrmo** [comment]
Works awesome, thanks so much! Feel free to close this, or leave it open as a "reminder" for when Marshmallow is ready.

Much appreciated!

**Comment by arrmo** [comment]
BTW, would be happy to try to help building it - yell if I can help out.

**Comment by pdsouza** [comment]
master is now on Marshmallow!

This will be available in the next release.

Closed in https://github.com/maruos/manifest/commit/4079f1912429d8257f19e44b8fc21f33d5d32748 and others.
