### ISSUE TITLE
geany settings

### ISSUE THREAD

**Issue by gadepall** [maruos/maruos#61]
I configured geany for running latex. It works fine, but settings were reset to default in next boot.  Is there a bug or did I make a mistake?

**Comment by pdsouza** [comment]
Hmm, can you give me steps to reproduce? I'll take a look.

Settings should be persistent across reboots as long as your geany settings were written back to the file system (assuming somewhere in your home directory?). I am unfamiliar with geany though.

**Comment by gadepall** [comment]
False alarm.  Everything works perfectly using geany.

**Comment by pdsouza** [comment]
Oh, ok great!

Feel free to close this if you don't run into any more issues with geany.
