### ISSUE TITLE
Any way to mount external volume? (both sshfs and nfs failed)

### ISSUE THREAD

**Issue by chepec** [maruos/maruos#65]
On freshly installed MaruOS v 0.3, running Jessie 3.4.0 ARMv7.

I am looking for a way to mount a drive from my NAS on MaruOS. I tried `sshfs`, which installed fine (`apt-get install sshfs`) but failed to mount (appears related to a bunch of old Debian bugs [1](https://lkml.org/lkml/2006/12/21/157), [2](https://lists.debian.org/debian-kernel/2006/12/msg00671.html), [3](http://askubuntu.com/questions/459296/could-not-open-moddep-file-lib-modules-3-xx-generic-modules-dep-bin-when-mo). So I abandoned that approach.

Next I tried setting up Jessie as an `nfs` client instead (I can live with only acessing the server inside my LAN), and `apt-get install rpcbind` went fine, but `apt-get install nfs-common` failed:

```
Job for nfs-common.serve failed.
invoke-rc.d: initscript nfs-common, action "start" failed.
```

I am a little confused, as it seems ARM in itself should not be the problem (there are reports of nfs clients or servers running on Raspberry Pi [4](http://www.htpcguides.com/configure-nfs-server-and-nfs-client-raspberry-pi/), [5](https://www.raspberrypi.org/forums/viewtopic.php?f=36&t=14500)) although I found some tangentially related bug reports [6](http://forums.debian.net/viewtopic.php?t=61955), [7](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=562737).

Has anyone else managed to mount a remote share on MaruOS/Jessie ARM? 
Edit: is this related to #51 and containers?

**Comment by pdsouza** [comment]
Thank you for the clear report!

The first issue is that NFS is not enabled in the Maru OS kernel. I was looking into this issue earlier and had a development kernel with NFS enabled, but I had issues getting nfs-common to install, likely similar to what you are seeing: https://groups.google.com/d/msg/maru-os/UFMQqIrBfPo/Bopv4PFeAgAJ. I wasn't able to root-cause it though, so I never enabled it in our release builds.

The second issue is that running in an LXC container complicates things even more, as seen with the issues mounting CIFS shares in #51. How exactly the container environment is affecting these network shares, I need to dig in more to find out.

This has come up a a few times, so it's obvious that this is a common use-case with Maru OS--I am going to make time to look into this this week and will update here as I learn more.

**Comment by pdsouza** [comment]
OK! I took a look at `sshfs` and I was able to get it to work! 

The key is to create the `/dev/fuse` device node since this is not created by default within the container (see [LXC #80](https://github.com/lxc/lxc/issues/80)):

    $ sudo mknod -m 666 /dev/fuse c 10 229

Then you can use sshfs as usual:

    $ sudo sshfs <user>@<host>:/path/to/mnt /mnt/<share>

Let me know how this goes. Hopefully this gives you a workaround until other network storage stuff like NFS works in Maru OS.

**Comment by chepec** [comment]
Fantastic! That works.

I noticed that the `mknod` command does not persist after reboots, and apparently neither does `/etc/fstab`, so I added a line to root's crontab, `sudo crontab -e` (had to `apt-get install cron` first):

```
@reboot /bin/mknod -m 666 /dev/fuse c 10 229 & mount /my-mountpoint
```

and `/etc/fstab` contains this sshfs mount config (which takes effect when `mount /my-mounpoint` is executed):

```
nashost:/sharedfolder /my-mountpoint fuse.sshfs defaults,_netdev,delay_connect, auto,allow_other 0 0
# nashost defined in root's ssh config file
```

Just an ugly hack of course, but as far as I can tell my sshfs mount now auto-mounts on every reboot. Really appreciate your help @pdsouza.

**Comment by pdsouza** [comment]
Thanks @chepec for confirming that this worked and sharing your solution to make it persistent! 

I am going to look at making this work out-of-the-box in the next version by creating essential devices nodes like `/dev/fuse` automatically during container initialization; this really should just work without any extra configuration needed on the user's end.
