### ISSUE TITLE
Maru 0.4 flo's /system is too full for installing gapps pico

### ISSUE THREAD

**Issue by pdsouza** [maruos/maruos#66]
More info: https://groups.google.com/forum/#!topic/maru-os/xkr2aBzNVA8

**Comment by pdsouza** [comment]
@TMartinPPC and I are working on a getting a new 0.4 build with the desktop build with `--minimal` enabled to open up more space on /system.

**Comment by pdsouza** [comment]
Looks like the `--minimal` option in blueprints is just barely not enough for the latest opengapps pico installer, although older versions of opengapps pico installers work ((they keep getting bigger over time...). We still need to trim a couple MBs more for pico.

**Comment by pdsouza** [comment]
Managed to bring the desktop image down significantly (50% savings) by removing `libreoffice*` packages on top of the standard `--minimal` target: https://github.com/maruos/blueprints/commit/51c91ef05b28eb23bf033e95c44c1785c2f7625e

We are currently testing flo builds with this new minimal desktop image.

**Comment by kdog31** [comment]
may I ask when we can expect this to be patched?

**Comment by pdsouza** [comment]
@kdog31 As soon as I get the green light from our flo maintainer @TMartinPPC, who is testing out the builds asap. I don't own flo unfortunately, so there is a little lag while we coordinate. Actually, if you want to help test and confirm our patch fixes this issue, you can find the release candidate update zip here: https://drive.google.com/open?id=0B4ZyDB8ct_ywbUVmTkt0YTNSTEE

**Comment by kdog31** [comment]
awesome, ill have a look at that now, however, I can't test desktop environment as slim port cable broke

**Comment by kdog31** [comment]
Maru is installed and running on flo, OpenGapps Pico is also installed and working fine, as is google play services. The device is running more or less as expected. However, when maru is booted plugging it into my desktop causes what I can only describe as a USB host crash (all USB devices loose power and continue to power cycle until either I unplug it, USB goes cold or the computer BSODs I suspect that it tries to pull too much current) I will try to replicate on other machines tomorrow and will keep you updated. if I can replicate on other machines I will upload a video showing what it does as it doesn't appear to leave a windows event log.

**Comment by pdsouza** [comment]
Thanks for the feedback! Good to hear that opengapps installs fine and device is working as expected. The USB issue is pretty weird...I would suspect that it has to do with your particular setup (your desktop and/or your flo unit) but yes, please keep us posted if you can reproduce this.

**Comment by kdog31** [comment]
That is good to know, as for the USB issue I will open another bug thread of I can reproduce it on another machine.

**Comment by kdog31** [comment]
Also regarding the USB issue, I beloved it has something to do with the OS as when it was fished with stock and lineage OS it behaved normally

**Comment by danielartdiaz** [comment]
What version of pico do you use? im trying it and im still getting the same error message. Its ARM - 6.0- Pico, correct?

**Comment by kdog31** [comment]
@danielartdiaz, I used open_gapps-arm-6.0-pico-20170321.zip i believe that is latest release. If it is any help I also nuked /system and /data with TWRP(version 3.1.0-0) before i flashed the release candidate and the gapps. if that dosn't work i would suggest looking into a gapps package called a-gapps (can be found [here](https://forum.xda-developers.com/android/general/gapps-gapps-6-0-1-minimal-t3276606)) it is ~40MB

on a different note

@pdsouza i was unable to replicate the USB problem on other machines, and it appears to have dissapeared on the computer it was affecting, i will keep you updated if it pops up again.

**Comment by pdsouza** [comment]
@kdog31 Thanks for the update! Keep us posted if it pops up again.

@danielartdiaz Please ensure that you are using the release candidate update zip (maru-v0.4-update-flo-9185c8a3.zip), it has a very similar name to the current release (maru-v0.4-update-flo-648299d7.zip). The exact link to the pico gapps download is http://opengapps.org/?arch=arm&api=6.0&variant=pico.

**Comment by kdog31** [comment]
@pdsouza will do

**Comment by kdog31** [comment]
the Debian environment is working through VNC so i assume it will work with a slimport cable, i also cannot browse by network in Debian, is this a known issue or is this done intentionally.

**Comment by pdsouza** [comment]
Ok great, good to hear VNC is working. And yes, Thunar has a few problems, one of them being Browse by network.

Our flo maintainer has also verified the release candidates are good and I will be uploading them to our releases shortly.

**Comment by pdsouza** [comment]
...and they are now available on http://maruos.com/#/downloads and our releases page!

Will keep this issue open a little longer in case anyone is still having trouble with installing gapps.

**Comment by TMartinPPC** [comment]
Should we close this issue?

**Comment by pdsouza** [comment]
@TMartinPPC Yeah, looks like this is good.
