### ISSUE TITLE
[Question] - Hardware support list for current MaruOS

### ISSUE THREAD

**Issue by dosida** [maruos/maruos#67]
Hey guys,

Is there a Hardware support list for MaruOS so far?

One that would include all types of supported phones and peripherals as of this moment.
It would be awesome to know before I decide to root my Motorola X Play and flash it with MaruOS to run a few tests... wouldn't want to brick my main cellphone.

Thanks in advance

**Comment by pdsouza** [comment]
Please see our [FAQ](https://github.com/maruos/maruos/wiki/FAQ#which-devices-are-officially-supported). 

We don't support any Motorola devices right now unfortunately--our focus is on Nexus.

**Comment by pdsouza** [comment]
Closing this since it's super old, please feel free to re-open if you have any further questions.
