### ISSUE TITLE
maroOS update lineageOS on nexus5 

### ISSUE THREAD

**Issue by cyanogenonlg5** [maruos/maruos#72]
I have lineageOS on my nexus5 (LG) 
1) I copied "maru-v0.4-update-hammerhead-dd793179.zip" on the download of my nexus5
2) started recovery mode 
3) wiped
4) started install
5) maru install began  but never ended

Can I use this "update zip" to get maru on my phone?

**Comment by pdsouza** [comment]
Yes, the update zip should work to do a fresh install even if you don't have Maru already installed on your device. I have never tried LineageOS, but it should be fine if you wipe the device. I have tested the update zip install via TWRP with the latest stock Android factory image on the Nexus 5.

Are you using TWRP? Can you get me the logs or a screenshot of where the install hangs? You may also want to do a quick data integrity check of your zipfile in case it is corrupted (unlikely, but you never know), please compare the SHA1 hash to the ones in this file: https://github.com/maruos/maruos/releases/download/v0.4/maru-v0.4-sha1sums.asc.txt

**Comment by cyanogenonlg5** [comment]
Yes, its TWRP.
Phone says: "Android is renewed"
"System is prepared"
...then window stays forever.
I have installed lineageos again.

Since I'm just a user, don't know about logs or screenshots on nexus5. sorry




On 17 April 2017 16:22:45 GMT+02:00, pdsouza <notifications@github.com> wrote:
>Yes, the update zip should work to do a fresh install even if you don't
>have Maru already installed on your device. I have never tried
>LineageOS, but it should be fine if you wipe the device. I have tested
>the update zip install via TWRP with the latest stock Android factory
>image on the Nexus 5.
>
>Are you using TWRP? Can you get me the logs or a screenshot of where
>the install hangs? You may also want to do a quick data integrity check
>of your zipfile in case it is corrupted (unlikely, but you never know),
>please compare the SHA1 hash to the ones in this file:
>https://github.com/maruos/maruos/releases/download/v0.4/maru-v0.4-sha1sums.asc.txt
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/maruos/maruos/issues/72#issuecomment-294494689

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cyanogenonlg5** [comment]
Hey!!! it worked!! thank you pdsouza !!



1) TWRP
2)WIPE (factory reset)
3)Back
4)Install
5)maru-v0.4.....df...zip
6)swipe to flash
(flashing file 1of1)
7)Updating partition details .... done
8)Wipe
9)Back
10)Reboot System
11)Do not install
----- google
_____  maru
and then ... the snowy mountains!

Thank You


On 17 April 2017 16:22:45 GMT+02:00, pdsouza <notifications@github.com> wrote:
>Yes, the update zip should work to do a fresh install even if you don't
>have Maru already installed on your device. I have never tried
>LineageOS, but it should be fine if you wipe the device. I have tested
>the update zip install via TWRP with the latest stock Android factory
>image on the Nexus 5.
>
>Are you using TWRP? Can you get me the logs or a screenshot of where
>the install hangs? You may also want to do a quick data integrity check
>of your zipfile in case it is corrupted (unlikely, but you never know),
>please compare the SHA1 hash to the ones in this file:
>https://github.com/maruos/maruos/releases/download/v0.4/maru-v0.4-sha1sums.asc.txt
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/maruos/maruos/issues/72#issuecomment-294494689

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pdsouza** [comment]
Oh, great news!! Looks like the wipe had to be done after flashing the zip? Either way, glad you were able to get it to work!

**Comment by pdsouza** [comment]
Closing this. Please feel free to re-open if you have any further issues.
