### ISSUE TITLE
Linux installer: wget target URL is now obsolete

### ISSUE THREAD

**Issue by pdsouza** [maruos/maruos#73]
Looks like the `51-android.rules` udev permissions file from AOSP was renamed to `51-android.txt`: https://source.android.com/source/initializing#configuring-usb-access. Users who need to download this file to give the installers access to their devices in fastboot mode will be stuck since wget will error out with 404.

This failure is also silent unfortunately due to the `-q` flag...

We need to update the Linux installer to use the correct URL.

## Workaround

If you are stuck on the installer after trying to run the `wget` command, please replace `http://source.android.com/source/51-android.rules` with `https://source.android.com/source/51-android.txt` in the installer message, i.e. please run this:

    $ wget -S -O - https://source.android.com/source/51-android.txt | sed "s/<username>/$USER/" | sudo tee /etc/udev/rules.d/51-android.rules; sudo udevadm control --reload-rules

**Comment by pdsouza** [comment]
Fixed in https://github.com/maruos/installer/commit/c5fad6acd46b248fe5103f1f548dcae70b23f44d.

**Comment by curiousercreative** [comment]
@pdsouza can this issue be closed?

**Comment by pdsouza** [comment]
@curiousercreative Keeping this open until the new installers are released in case others run into this.

**Comment by pdsouza** [comment]
v0.4.1 contains this fix, please use the latest installers!
