### ISSUE TITLE
UNINSTALL

### ISSUE THREAD

**Issue by xk** [maruos/maruos#75]
Hi,

I want to give the phone to my daughter, how can I revert it to normal?

**Comment by pdsouza** [comment]
Sorry to see you go! 

You can run the uninstall script from our installer zips and follow along. It will walk you through downloading a factory image from https://developers.google.com/android/images#hammerhead and flashing it to restore your device to factory settings. Please feel free to keep this issue open if you have any questions during the process.

**Comment by xk** [comment]
Done. No issues at all, worked seamlessly. Thank you! (closing)
