### ISSUE TITLE
sshd enabled by default on the default maru account is a security risk

### ISSUE THREAD

**Issue by pdsouza** [maruos/maruos#76]
Some important concerns were raised on [this HN thread](https://news.ycombinator.com/item?id=14354616) about having sshd enabled on the default maru account with default password.

A quick fix for this is to disable sshd out-of-the-box, and have users explicitly enable it. This was the way Maru used to do it before background desktop start-up was introduced in v0.3: https://github.com/maruos/maruos/issues/22#issuecomment-229692011, https://github.com/maruos/maruos/issues/5#issuecomment-249022033.

Something to think about in the longer term is account management in general. Ideally we don't have a default account at all--instead, we have a welcome app on the phone that starts up on first boot, and prompts the user to set up an account and password for Maru Desktop. sshd can then be enabled after a password has been set.

Edit: updated HN thread link to point to specific comment

**Comment by pdsouza** [comment]
For any users running v0.3 and up who don't want to wait for a new patched release, the fix for this is very easy to apply yourself: simply change the default password for the default `maru` account.

## 1. Change the default maru account password

If you are using Maru Desktop graphically with an HDMI display and BT keyboard/mouse or over VNC:

1. Open up a Terminal (Applications Menu > Terminal Emulator)
2. Type `passwd maru`
3. Follow the instructions to set your new password*

Otherwise, if you are using Maru Desktop via ssh:

1. ssh into the default `maru` account (`ssh maru@<your-ip-address>`)
2. Type `passwd`
3. Follow the instructions to set your new password*

Please remember to use a strong password!

**If you are prompted for the current password before setting your new password, the default password is "maru".*

## 2. (OPTIONAL) Disable sshd if you don't need ssh access to your desktop

1. Open up a Terminal (Applications Menu > Terminal Emulator) or ssh into your account
2. Type `sudo systemctl stop ssh`
3. Type `sudo systemctl disable ssh`

**Comment by pdsouza** [comment]
SSH services have been disabled by default in https://github.com/maruos/blueprints/commit/690c3b676aed974f9c9e9423455ad3e15426c89e.

Keeping this issue open as a notice until the new release is ready.

**Comment by regular** [comment]
How about creating a ssh key pair in the install script and copying the public key into ~maru/.ssh/authorized_keys. Password authentication can then be disabled by default (in /etc/sshd.conf) and thus having sshd on-by-default would be perfectly safe!

In order to login, the user would have to use `ssh -i <private-key-file> maru@<ip>`

**Comment by regular** [comment]
I do not have an external screen (yet) and now I don't know how I can enable sshd "from the outside". I guess, it must be some combination of `adb shell` and `chroot`?

**Comment by regular** [comment]
I just found that (on Android) you can go to Settings > Desktop > Dashboard and that you can start the maru container from there without having a display connected. (maybe that's  good candidate for the FAQ)

**Comment by pdsouza** [comment]
@regular Sorry for the confusion--I agree that isn't obvious. I've updated https://github.com/maruos/maruos/wiki/Tips on how to start the desktop container in the background.

**Comment by regular** [comment]
Thank you @pdsouza and thank you even more for your great work here!

**Comment by pdsouza** [comment]
sshd is disabled by default in v0.4.1, please upgrade! v0.4.1 release notes (including upgrade notices) and downloads are available here: https://github.com/maruos/maruos/releases/tag/v0.4.1

**Comment by jeff-hogan** [comment]
Found a solution for starting ssh without a SlimPort adapter, this worked on Nexus 7.
1) adb shell
2) cd /data/maru/containers/jessie/rootfs/home/maru
3) vi .xsession
    (paste the following into .xsession)
    echo maru | sudo -S systemctl enable ssh
    echo maru | sudo -S systemctl start ssh
4) chmod 755 .xsession
5) chown u9_system:u9_system .xsession
6) exit shell and start system
7) Settings -> Desktop -> Dashboard -> On
8) Then you can ssh in and delete .xsession

**Comment by pdsouza** [comment]
@jeff-hogan Thanks for the tip! Feel free to add to our [tips wiki](https://github.com/maruos/maruos/wiki/Tips) in case it helps others!

**Comment by prateek33** [comment]
Running the command: cd /data/maru/containers/jessie/rootfs/home/maru
produces an error:
127|shell@flo:/data $ cd /data/maru/containers/jessie/rootfs/home/maru         
/system/bin/sh: cd: /data/maru/containers/jessie/rootfs/home/maru: Permission denied

I tried ADB root but:
~/Downloads/maru-v0.4.1-installer-flo-mac-d23147b4$ adb root
adbd cannot run as root in production builds

Any help? Without SSH, installing MaruOS useless for me. I need the SSH access

**Comment by pdsouza** [comment]
@prateek33 Ah yeah, you will need root privileges to directly access `/data/maru`. I believe @jeff-hogan must have rooted his build. I definitely agree that we need an easier way to enable SSH in a headless setup like yours...it would be nice to have an "Enable SSH" toggle in Settings > Dashboard that could set up SSH behind the scenes for you. No guarantees I can work on it atm but it's definitely on my TODO list -- keep an eye on https://github.com/maruos/maruos/issues/78.

**Comment by sergioamr** [comment]
I know it is an old thread, but this is a more up to date list of actions to do this with this latest release.

First, get root for ADB
`Settings > System > Developer options > Root access > ADB only` 
Edit a file .xsession, if in Windows, be careful with encoding and EOL.

.xsession
`echo maru | sudo -S systemctl enable ssh
echo maru | sudo -S systemctl start ssh`

Upload the file to the phone
`adb root
adb push .xsession /data/maru/containers/default/rootfs/home/maru/.
adb shell` 

In the latest version the default folder is here:
`$ cd /data/maru/containers/default/rootfs/home/maru
$ chmod 755 .xsession
$ chown u9_system:u9_system .xsession
`
Restart the desktop
Settings -> Desktop -> Dashboard -> On

the .xsession-errors will report any error related to .xsession

**Comment by pdsouza** [comment]
@sergioamr Awesome, thanks for the updated instructions!
