### ISSUE TITLE
Support addon.d scripts

### ISSUE THREAD

**Issue by pdsouza** [maruos/maruos#77]
Right now, dirty upgrades of Maru+gapps require a [re-flash of gapps](https://github.com/maruos/maruos/wiki/Upgrading#gapps). It may be possible to preserve gapps between dirty upgrades by supporting addon.d scripts.

More info:
https://github.com/opengapps/opengapps/wiki/FAQ#18-is-it-necessary-to-reinstall-open-gapps-every-time-i-update-my-rom

**Comment by meiser79** [comment]
Can be closed as LineageOS supports addon.d script by default.

**Comment by pdsouza** [comment]
@meiser79 Thanks, closing.
