### ISSUE TITLE
How to setup without HDMI display? 

### ISSUE THREAD

**Issue by fiveseven808** [maruos/maruos#78]
So none of my slimport adapters are very reliable, and I don't have one here at work. My phone is flashed and everything seems good, except I can't seem to find any information on if there's a way to ssh into my phone without having to connect to a monitor first. 

Can anyone help me?

**Comment by fiveseven808** [comment]
I guess since having SSHD automatically enabled is a security issue, how about we make it an enableable option? I.e. drop an empty file somewhere, or change a file through adb/android to enable it on the Maru side? That way there's a conscious effort to go and enable it, thus hopefully implying that it will become secured. 

I'd rather not flash my phone again, but I really want to play with this, but I can't seem to find my slimport adapter!

**Comment by fiveseven808** [comment]
I've flashed it, I can SSH to it, but I can't seem to find the default username anywhere.... Can anyone help me?

**Comment by pdsouza** [comment]
You need to connect to a monitor first to enable sshd as of 0.4.1: https://github.com/maruos/maruos/wiki/Tips#access-your-desktop-with-ssh.

Creating a file called `ssh` could be an option like with the Raspberry Pi: https://www.raspberrypi.org/documentation/remote-access/ssh/. The trick would be deciding where to place the file since non-root adb can only write to world-writable directories on the data partition. `/data/media` ("/sdcard") is an option but any other potentially malicious process/app could drop off a file there too.

A better/safer option may be to have a toggle in Settings > Desktop > Dashboard to enable SSH that can only be accessed by the user.

**Comment by MatrixManAtYrService** [comment]
I just flashed my phone via [Magic-Device-Tool](https://github.com/MariusQuabeck/magic-device-tool).  I found this post, but on a whim decided to try `ssh maru@<phone-ip>` anyhow, and it worked.

Does the magic device tool install an older version which has ssh enabled by default, or is something else going on here?

I plan to use Maru as a server, so I was hoping to avoid having to buy a slimport adapter at all.  So far it looks like I might be able to pull it off.

**Comment by pdsouza** [comment]
@MatrixManAtYrService Yep, looks like magic-device-tool uses v0.4 which has ssh enabled by default. This was disabled in 0.4.1 for security reasons until a better solution for enabling ssh is worked out. For now, you can use 0.4 if you don't have a slimport adapter around. 

Permalink to 0.4 release for others who don't have a slimport adapter around and would like to ssh in quickly: https://github.com/maruos/maruos/releases/tag/v0.4

**Comment by fiveseven808** [comment]
What if instead of a "file" we make a flashable package that gets flashed through the recovery like TWRP? 

Making a toggable setting would be so much more amazing though! Can this be done? Also, would we be able to create a toggle setting for VNC as well (to allow on-phone control).

**Comment by fightforlife** [comment]
I really want to try using Maru OS as a headless server on my old Nexus 5X.
I dont have a Chromecast or a BT Keyboard. Is there any way to enable the SSH service without the interface?

**Comment by pdsouza** [comment]
I wish I had a better answer but unfortunately you need to login graphically first to enable SSH the very first time. 

There are quite a few users who want to use Maru in a headless setup so this needs to be fixed. @utzcoz has actually done some work to allow us to run commands from Android within the container (we use this to enable/disable pointer and keyboard events dynamically between Android and Maru Desktop) - perhaps we can create a small script to re-enable SSH services using this approach and make it an option in Settings.

**Comment by luka177** [comment]
There is a way without display. 
1.Get root (go to settings developer mode enable adb and root for adb) idk is it needed
2.run adb root on pc with connected phone
3. run adb shell
4. lxc-start -n default
wait and you are in login shell login enable ssh vnc change password etc etc

**Comment by luka177** [comment]
So any more problems, or issue can be closed?

**Comment by utzcoz** [comment]
@pdsouza could we add those suggestions to doc and close this issue?

**Comment by zhou0** [comment]
> There is a way without display.
> 1.Get root (go to settings developer mode enable adb and root for adb) idk is it needed
> 2.run adb root on pc with connected phone
> 3. run adb shell
> 4. lxc-start -n default
> wait and you are in login shell login enable ssh vnc change password etc etc

what is the login and password?

**Comment by utzcoz** [comment]
> > There is a way without display.
> > 1.Get root (go to settings developer mode enable adb and root for adb) idk is it needed
> > 2.run adb root on pc with connected phone
> > 3. run adb shell
> > 4. lxc-start -n default
> > wait and you are in login shell login enable ssh vnc change password etc etc
> 
> what is the login and password?

The default username : maru
The default password: maru

**Comment by pdsouza** [comment]
> @pdsouza could we add those suggestions to doc and close this issue?

@utzcoz Added in https://github.com/maruos/maruos/commit/344578350d7bc4e338a5d4fa5fc319b5d22fc22c.

Closing this issue as the workaround has been added to our docs.
