### ISSUE TITLE
Turn off MaruOS Desktop? 

### ISSUE THREAD

**Issue by fiveseven808** [maruos/maruos#79]
Is there a gentle way of doing this? I've done a "sudo shutdown now" but the banner in the notification window still remains (even though it's technically off). 

What is the correct procedure for this?

**Comment by pdsouza** [comment]
The notification is out of state with the desktop since you shut it down from the command-line. The general way of doing it is going to Settings > Desktop > Dashboard and flicking the switch to Off. If you visit the Dashboard the notification should sync up and disappear.

**Comment by fiveseven808** [comment]
Alright, I will use that method. Thanks!
