### ISSUE TITLE
Logitech K810 bluetooth keyboard fails to type

### ISSUE THREAD

**Issue by gantner** [maruos/maruos#8]
Just wanted to make a note somewhere that the Logitech K810 bluetooth keyboard pairs with Maru Nexus 5 but is not able do anything in either Android or Debian. Neither system seemed to register any key press at all. This isn't the recommended keyboard but I had one available and gave it a shot.

**Comment by gantner** [comment]
Well, after I connected a bluetooth mouse and open ice weasel, I re-added the k810 while using the desktop - connected and worked fine. Not sure what caused the original hiccup.

**Comment by pdsouza** [comment]
Glad to hear you got this to work! Just a note that Maru will drop all the key events from Android right now so you don't get duplicate key events on both the desktop and phone,. That means you won't be able to type in Android with your BT keyboard right now, but it will register on the desktop. This is an area that I'd like to improve so you can select where to route your key presses too--either Android or the desktop.

**Comment by gantner** [comment]
Yes - that would be handy. I haven't delved deeply into the documentation so I'm not sure if this a hypervisor / VM or not but one thought that struck me was I could be more productive if a virtual mirror of my android was a window on my Debian desktop. Then I could respond to text, phone calls and such without leaving my keyboard.
