### ISSUE TITLE
[Feature Request] Optional "Disable bluetooth redirection"

### ISSUE THREAD

**Issue by fiveseven808** [maruos/maruos#83]
Having linux on your phone is awesome! Having to go through a GUI to access it with a keyboard is not! 

There are times where I'd like to just access linux on my phone via shell, but I need the Maru OS desktop running so I can do that. But when I do that, my bluetooth keyboard attached to my phone gets redirected to the Maru OS desktop. 

I would like to be able to SSH from android into Maru OS on my phone and control it via the bluetooth keyboard I have currently hooked up. 

Can this be done?

**Comment by pdsouza** [comment]
In other words, you would like to be able to choose where to send input events, either the phone or desktop, right? https://github.com/maruos/maruos/issues/12

**Comment by fiveseven808** [comment]
That is correct!

**Comment by pdsouza** [comment]
We have a proposal to fix this in https://github.com/maruos/maruos/issues/97.

**Comment by pdsouza** [comment]
This should be fixed in our 0.6 releases thanks to #97. If you don't have an external display attached, your BT keyboard will be directed to your Android so you can use it for SSH.

Please feel free to re-open if you have further issues.
