### ISSUE TITLE
Uninstalling maru os

### ISSUE THREAD

**Issue by alvamao** [maruos/maruos#86]
I am currently running 0.3 maru os, and I am trying to uninstall it on the nexus 5. However, whenever I try to uninstall the os, I get this error message. 

'flash-all' is not recognized as an internal or external command,
operable program or batch file.

Can anyone help with uninstalling? thanks

**Comment by TMartinPPC** [comment]
I have a few questions for you. Are you just trying to go back to the stock OS on your Nexus 5? What OS are you running the flash-all command in (windows, linux, mac)? Do you have TWRP, or another custom recovery, installed on your Nexus 5?

**Comment by alvamao** [comment]
Yes, I am trying to go back to the stock Android os, I have a Windows os, and I do not have any custom recovery or TWRP. I had downloaded Maru straight from stock Android and now I am trying to switch it back.

**Comment by TMartinPPC** [comment]
Okay. I think the issue is you don't have adb and fastboot tools installed. Go [here](https://developer.android.com/studio/releases/platform-tools.html) and download the platform tools for windows. Extract the zip and move all of the contents to folder you have the flash-all.bat in. Once it's all there, try double clicking the flash-all.bat again.

**Comment by alvamao** [comment]
Ok, I have extracted all of the files to the folder, but the uninstall program still doesnt work. 
![image](https://user-images.githubusercontent.com/31043461/29329891-627f575a-81c5-11e7-909a-12f940b0bb92.png)

**Comment by TMartinPPC** [comment]
Move the contents of the "platform-tools" folder into that folder, not the "platform-tools" folder itself.

**Comment by alvamao** [comment]
Ok that didn't work, I am still getting the same error message.
![image](https://user-images.githubusercontent.com/31043461/29330128-3e184682-81c6-11e7-8f1b-5d1429a64ca7.png)

**Comment by TMartinPPC** [comment]
Hmm...let me jump into my windows VM and repeat the same steps.

**Comment by alvamao** [comment]
Ok, thanks for helping!

**Comment by alvamao** [comment]
This is the error message I am getting. 
![image](https://user-images.githubusercontent.com/31043461/29330326-d3a67fd4-81c6-11e7-8c2e-6481caffc5ef.png)

**Comment by TMartinPPC** [comment]
Instead of running the uninstall script, just double click on the flash-all.bat inside that folder.

**Comment by alvamao** [comment]
Ok, now I am getting this message.
![image](https://user-images.githubusercontent.com/31043461/29330549-85ed8106-81c7-11e7-8ee5-f71fb9095a2a.png)

**Comment by TMartinPPC** [comment]
Could you move the entire hammerhead-m4b30z folder to the base of the c:/ drive? I don't know if the space in the path to that folder/files could cause issues or not.

**Comment by alvamao** [comment]
I have moved the folder to the c:/ drive but I am still getting the same error message. 
![image](https://user-images.githubusercontent.com/31043461/29331275-df06f1c6-81c9-11e7-9b50-a8ef9b12221f.png)

**Comment by TMartinPPC** [comment]
Can you tell me the contents of the image-hammerhead-m4b30z.zip?

**Comment by alvamao** [comment]
These are the contents of the folder. 
![image](https://user-images.githubusercontent.com/31043461/29331549-caee675e-81ca-11e7-87ee-2788a56e648e.png)

**Comment by TMartinPPC** [comment]
Okay. Copy those into the the hammerhead-m4b30z folder above the folder you are in, open cmd in hammerhead-m4b30z and run all the commands from number 8 [here](http://www.droidviews.com/how-to-restoreunroot-nexus-5-by-flashing-factory-images/). First and third commands will be a little different.

1st will be: fastboot flash bootloader bootloader-hammerhead-hhz20h.img

and 3rd will be: fastboot flash radio radio-hammerhead-m8974a-2.0.50.2.30.img

**Comment by alvamao** [comment]
Sorry, how do I open cmd in hammerhead-m4b30z again?

**Comment by alvamao** [comment]
Wait nevermind I got it.

**Comment by TMartinPPC** [comment]
Hold shift and right click inside the folder. Should see an option "Open command window here"

**Comment by alvamao** [comment]
Ok I keep getting this error message. 
![image](https://user-images.githubusercontent.com/31043461/29332549-67f547d6-81ce-11e7-8feb-2914925bcfb2.png)

**Comment by TMartinPPC** [comment]
just add the ./ in front of the fastboot command each time

example: ./fastboot flash bootloader bootloader-hammerhead-hhz20h.img

**Comment by TMartinPPC** [comment]
Oops....I mean .\

**Comment by alvamao** [comment]
./ worked as well, you're all good. However, whenever I try to enter the command ./fastboot flash system system.img, an error message pops up. 
![image](https://user-images.githubusercontent.com/31043461/29332930-cb3f3a30-81cf-11e7-9548-70e50be9fc3e.png)

**Comment by alvamao** [comment]
This is my folder right now. 
![image](https://user-images.githubusercontent.com/31043461/29333017-3185e398-81d0-11e7-9527-e280f0164d4a.png)

**Comment by alvamao** [comment]
Haha I just realized I undid the copy paste. Oops.

**Comment by alvamao** [comment]
Ok I have finished the cmd scripts, and my phone is rebooting.

**Comment by alvamao** [comment]
Ok, Nexus is back to normal, Thanks for helping me out and being patient with me! You've been a massive help.
