### ISSUE TITLE
Kernel Options

### ISSUE THREAD

**Issue by arrmo** [maruos/maruos#9]
Hi,

Any info available on what kernel options exist? FYI, I did install ElementalX (from TWRP), seems to be working fine.

Thanks!

**Comment by pdsouza** [comment]
I just put up the kernel repo, check out the config here: https://github.com/maruos/android_kernel_msm/blob/hammerhead-3.4-lollipop-mr1.1/arch/arm/configs/maru-hammerhead_defconfig

I'm unfamiliar with the ElementalX kernel but that's cool that it works! The desktop starts up fine?

**Comment by arrmo** [comment]
Thanks!

Yes, no issues at all - and the "control" app works as well - more info, links below.
http://elementalx.org/
https://play.google.com/store/apps/details?id=flar2.exkernelmanager&hl=en

**Comment by pdsouza** [comment]
Oh great, thanks for the info!

Happy to answer any other questions on this topic if you have them, otherwise feel free to close this issue.

**Comment by arrmo** [comment]
Thanks!
