### ISSUE TITLE
Feature request: MultiROM primary support

### ISSUE THREAD

**Issue by vercas** [maruos/maruos#90]
It would be really nice if I could use Maru OS as my primary ROM with MultiROM. I really do not want to keep a vanilla(-ish) Android installation just so I never use it.  
This will require adding the kexec-hardboot patch to the kernel.  

Quick Googlin' yielded [this patch](https://gist.github.com/Tasssadar/7833796) for Nexus 5 support.

**Comment by luka177** [comment]
Probably this must be closed, as multirom id=s dead and have no SAR support.

**Comment by pdsouza** [comment]
@luka177 Thanks for the update!

Closing.
