### ISSUE TITLE
Consult about the android version in * MadurOS *

### ISSUE THREAD

**Issue by renzoneru** [maruos/maruos#91]
I have not tried this interface yet and I am very interested in testing it on a very powerful Android terminal with a good CPU and GPU

I've been reading in forums and it indicates that this OS
"Maru also wants us to connect our Android device to a monitor, mouse and keyboard to work like a PC, and for this they have announced that they are developing a ROM that includes two operating systems: Android 5.1 Lollipop for the screen of our mobile phone and Debian for our monitor screen. "

Do you necessarily have to be an Android 5.1?
that version of android is outdated and I would like to put a version of android more recent as the Android 7.1 Nougat or even the Android 8.0 Oreo

it's possible?

**Comment by pdsouza** [comment]
Our latest official build runs on Android 6 Marshmallow. We also have an experimental Android 7.1 Nougat branch that is currently in development for the Nexus 5X.

Some of our community members have unofficial ports for various other newer devices, such as the HTC 10 that runs on Nougat as well: https://groups.google.com/d/msg/maru-os-dev/3mFTNIapiYA/E7xnO4dgAQAJ

**Comment by pdsouza** [comment]
@renzoneru Our upcoming release (0.6) runs on Android 8.1 Oreo. You can try out our early builds [here](https://github.com/maruos/builds/releases).

**Comment by pdsouza** [comment]
0.6 has been released and moves Maru to Android 8.1 Oreo. Closing this.
