### ISSUE TITLE
Manual start

### ISSUE THREAD

**Issue by Diporas** [maruos/maruos#93]
Is it possible to start maru os manually not from settings menu but from shell? To add some clearness, I connect to my router via then connect to my nexus via adb. How can I start maru os then?

**Comment by pdsouza** [comment]
Thank you for your question and for your interest in Maru OS!

If you have root access, you can use the `lxc-start` binary to start Maru Desktop and have access to a login shell:

    adb-shell# lxc-start -n jessie

We have had quite a few requests for a "headless" setup and hope to make this process as smooth as possible in the future. Maru Desktop was originally designed mainly for use on an external display so some of these things are less obvious than they should be.

**Comment by Diporas** [comment]
Thanks, it works. Also there is known issue that system uses only one core instead of 4, though it works good anyway, it would be great if all perfomance could be used.

**Comment by pdsouza** [comment]
Yes, a fix that allows all cores to be utilized has been sitting in our dev branches for a long time now as I was on hiatus from the project for a bit...and it kind of got lost in the stack as we were working on transitioning to Android N. But it will make it to our next release!

**Comment by utzcoz** [comment]
> Yes, a fix that allows all cores to be utilized has been sitting in our dev branches for a long time now as I was on hiatus from the project for a bit...and it kind of got lost in the stack as we were working on transitioning to Android N. But it will make it to our next release!

Hi @pdsouza , I have saw some lxc config for cpu utilization, is it supported by MaruOS 0.6/0.7 alreay?

**Comment by pdsouza** [comment]
Hi @utzcoz, yes this fix is available on Maru 0.6 for a while now :)

See https://maruos.com/blog/2019/announcing-maru-0.6-okinawa.html#performance-improvements for more info.

**Comment by utzcoz** [comment]
> Hi @utzcoz, yes this fix is available on Maru 0.6 for a while now :)
> 
> See https://maruos.com/blog/2019/announcing-maru-0.6-okinawa.html#performance-improvements for more info.

Thanks for response. Looks like all problems of this issue are fixed and released. I will close this issue, and @Diporas feel free to reopen it if you have any problem.
