### ISSUE TITLE
Can't connect Android cast device after starting desktop from settings

### ISSUE THREAD

**Issue by utzcoz** [maruos/maruos#98]
If I start desktop from settings firstly, and then try to connect Android `cast` device(not `ChromeCast`), it failed.  I guess there is a bug or my device's problem, the later is more probable, I think. I will debug source to check the process of connecting Android `cast` in this occasion.

@pdsouza I'm sorry I can't use `ChromeCast` to test the problem, because the `ChromeCast` can't be used in there(some known and terrible reason).

**Comment by utzcoz** [comment]
@pdsouza If I stop the desktop after disconnecting Android `cast` device, and then reconnect the Android `cast` device, it works fine. So it's not my device's problem. The test says we can't connect Android `cast` when the desktop is running in background.

**Comment by pdsouza** [comment]
@utzcoz Interesting! 

`75-persistent-net-generator.rules` is used to prevent Debian from renaming the network interfaces that Android adds. Maybe this was migrated to another rules file in stretch? I will need to look at `80-net-setup-link.rules`. We can put a blank file just like with `75-persistent-net-generator.rules` to prevent it from running.

**Comment by utzcoz** [comment]
@pdsouza [Change logs for systemd source package in Stretch](https://blueprints.launchpad.net/debian/stretch/+source/systemd/+changelog) has the information about deprecating old `75-persistent-net-generator.rules`.

**Comment by pdsouza** [comment]
@utzcoz Just came across this issue on my device (Nexus 5X) when toggling Wi-Fi on and off after the desktop is running (#102). Overriding `/lib/udev/rules.d/80-net-setup-link.rules` fixes it. I will be pushing a patch to fix this in blueprints shortly.

**Comment by pdsouza** [comment]
Fixed in https://github.com/maruos/blueprints/commit/7c203c21fff25c061770962a08c88d169e35c301.

Your cast device should work out of the box now!

**Comment by utzcoz** [comment]
@pdsouza Thanks your patch.
